export const PAGE6_TRANSCRIPT = [
    { "audioWord": "Atlas", "start": 0.0, "end": 0.56, "pageWordId": "atlas-1", "matchType": "matched" },
    { "audioWord": "–", "start": 0.56, "end": 0.9, "pageWordId": "atlas-2", "matchType": "matched" },
    { "audioWord": "a", "start": 0.9, "end": 1.24, "pageWordId": "atlas-3", "matchType": "matched" },
    { "audioWord": "collection", "start": 1.24, "end": 1.56, "pageWordId": "atlas-4", "matchType": "matched" },
    { "audioWord": "of", "start": 1.56, "end": 1.84, "pageWordId": "atlas-5", "matchType": "matched" },
    { "audioWord": "maps.", "start": 1.84, "end": 2.2, "pageWordId": "atlas-6", "matchType": "matched" },

    { "audioWord": "An", "start": 2.84, "end": 3.06, "pageWordId": "an-1", "matchType": "matched" },
    { "audioWord": "atlas", "start": 3.06, "end": 3.34, "pageWordId": "an-2", "matchType": "matched" },
    { "audioWord": "is", "start": 3.34, "end": 3.54, "pageWordId": "an-3", "matchType": "matched" },
    { "audioWord": "a", "start": 3.54, "end": 3.82, "pageWordId": "an-4", "matchType": "matched" },
    { "audioWord": "special", "start": 3.82, "end": 4.1, "pageWordId": "an-5", "matchType": "matched" },
    { "audioWord": "book", "start": 4.1, "end": 4.38, "pageWordId": "an-6", "matchType": "matched" },
    { "audioWord": "that", "start": 4.38, "end": 4.66, "pageWordId": "an-7", "matchType": "matched" },
    { "audioWord": "contains", "start": 4.66, "end": 5.1, "pageWordId": "an-8", "matchType": "matched" },
    { "audioWord": "many", "start": 5.1, "end": 5.5, "pageWordId": "an-9", "matchType": "matched" },
    { "audioWord": "different", "start": 5.5, "end": 5.84, "pageWordId": "an-10", "matchType": "matched" },
    { "audioWord": "kinds", "start": 5.84, "end": 6.14, "pageWordId": "an-11", "matchType": "matched" },
    { "audioWord": "of", "start": 6.14, "end": 6.36, "pageWordId": "an-12", "matchType": "matched" },
    { "audioWord": "maps.", "start": 6.36, "end": 6.7, "pageWordId": "an-13", "matchType": "matched" },

    { "audioWord": "Open", "start": 7.22, "end": 7.42, "pageWordId": "open-1", "matchType": "matched" },
    { "audioWord": "the", "start": 7.42, "end": 7.74, "pageWordId": "open-2", "matchType": "matched" },
    { "audioWord": "atlas", "start": 7.74, "end": 8.02, "pageWordId": "open-3", "matchType": "matched" },
    { "audioWord": "and", "start": 8.02, "end": 8.54, "pageWordId": "open-4", "matchType": "matched" },
    { "audioWord": "discover", "start": 8.54, "end": 9.08, "pageWordId": "open-5", "matchType": "matched" },
    { "audioWord": "how", "start": 9.08, "end": 9.5, "pageWordId": "open-6", "matchType": "matched" },
    { "audioWord": "each", "start": 9.5, "end": 9.82, "pageWordId": "open-7", "matchType": "matched" },
    { "audioWord": "map", "start": 9.82, "end": 10.12, "pageWordId": "open-8", "matchType": "matched" },
    { "audioWord": "helps", "start": 10.12, "end": 10.44, "pageWordId": "open-9", "matchType": "matched" },
    { "audioWord": "us", "start": 10.44, "end": 10.74, "pageWordId": "open-10", "matchType": "matched" },
    { "audioWord": "understand", "start": 10.74, "end": 11.14, "pageWordId": "open-11", "matchType": "matched" },
    { "audioWord": "the", "start": 11.14, "end": 11.38, "pageWordId": "open-12", "matchType": "matched" },
    { "audioWord": "world", "start": 11.38, "end": 11.7, "pageWordId": "open-13", "matchType": "matched" },

    { "audioWord": "explore", "start": 14.3, "end": 14.66, "pageWordId": "item1-1", "matchType": "matched" },
    { "audioWord": "the", "start": 14.66, "end": 14.9, "pageWordId": "item1-2", "matchType": "matched" },
    { "audioWord": "atlas", "start": 14.9, "end": 15.36, "pageWordId": "item1-3", "matchType": "matched" },

    { "audioWord": "discover", "start": 15.76, "end": 16.1, "pageWordId": "item2-1", "matchType": "matched" },
    { "audioWord": "three", "start": 16.1, "end": 16.38, "pageWordId": "item2-2", "matchType": "matched" },
    { "audioWord": "types", "start": 16.38, "end": 16.7, "pageWordId": "item2-3", "matchType": "matched" },
    { "audioWord": "of", "start": 16.7, "end": 16.98, "pageWordId": "item2-4", "matchType": "matched" },
    { "audioWord": "maps", "start": 16.98, "end": 17.24, "pageWordId": "item2-5", "matchType": "matched" },

    { "audioWord": "complete", "start": 17.88, "end": 18.32, "pageWordId": "item3-1", "matchType": "matched" },
    { "audioWord": "the", "start": 18.32, "end": 18.54, "pageWordId": "item3-2", "matchType": "matched" },
    { "audioWord": "journey.", "start": 18.54, "end": 18.82, "pageWordId": "item3-3", "matchType": "matched" }
];
