export const PAGE11_TRANSCRIPT = [
    { "audioWord": "Why", "start": 0.0, "end": 0.36, "pageWordId": "whyUseTitle-1", "matchType": "matched" },
    { "audioWord": "are", "start": 0.36, "end": 0.62, "pageWordId": "whyUseTitle-2", "matchType": "matched" },
    { "audioWord": "physical", "start": 0.62, "end": 0.98, "pageWordId": "whyUseTitle-3", "matchType": "matched" },
    { "audioWord": "maps", "start": 0.98, "end": 1.24, "pageWordId": "whyUseTitle-4", "matchType": "matched" },
    { "audioWord": "useful?", "start": 1.24, "end": 1.94, "pageWordId": "whyUseTitle-5", "matchType": "matched" },

    { "audioWord": "planning", "start": 4.16, "end": 4.5, "pageWordId": "whyUse-0-desc-1", "matchType": "matched" },
    { "audioWord": "outdoor", "start": 4.5, "end": 4.94, "pageWordId": "whyUse-0-desc-2", "matchType": "matched" },
    { "audioWord": "trips", "start": 4.94, "end": 5.34, "pageWordId": "whyUse-0-desc-3", "matchType": "matched" },
    { "audioWord": "and", "start": 5.34, "end": 6.0, "pageWordId": "whyUse-0-desc-4", "matchType": "matched" },
    { "audioWord": "finding", "start": 6.0, "end": 6.4, "pageWordId": "whyUse-0-desc-5", "matchType": "matched" },
    { "audioWord": "paths", "start": 6.4, "end": 6.86, "pageWordId": "whyUse-0-desc-6", "matchType": "matched" },
    { "audioWord": "through", "start": 6.86, "end": 7.22, "pageWordId": "whyUse-0-desc-7", "matchType": "matched" },
    { "audioWord": "nature.", "start": 7.22, "end": 7.62, "pageWordId": "whyUse-0-desc-8", "matchType": "matched" },

    { "audioWord": "learn", "start": 8.88, "end": 9.08, "pageWordId": "whyUse-1-desc-1", "matchType": "matched" },
    { "audioWord": "about", "start": 9.08, "end": 9.46, "pageWordId": "whyUse-1-desc-2", "matchType": "matched" },
    { "audioWord": "different", "start": 9.46, "end": 9.88, "pageWordId": "whyUse-1-desc-3", "matchType": "matched" },
    { "audioWord": "landscapes", "start": 9.88, "end": 10.36, "pageWordId": "whyUse-1-desc-4", "matchType": "matched" },
    { "audioWord": "landscapes", "start": 9.88, "end": 10.36, "pageWordId": "whyUse-1-desc-5", "matchType": "matched" },
    { "audioWord": "on", "start": 10.36, "end": 10.7, "pageWordId": "whyUse-1-desc-6", "matchType": "matched" },
    { "audioWord": "earth.", "start": 10.7, "end": 10.9, "pageWordId": "whyUse-1-desc-7", "matchType": "matched" },

    { "audioWord": "see", "start": 12.56, "end": 12.72, "pageWordId": "whyUse-2-desc-1", "matchType": "matched" },
    { "audioWord": "where", "start": 12.72, "end": 12.96, "pageWordId": "whyUse-2-desc-2", "matchType": "matched" },
    { "audioWord": "water", "start": 12.96, "end": 13.28, "pageWordId": "whyUse-2-desc-3", "matchType": "matched" },
    { "audioWord": "flows", "start": 13.28, "end": 13.68, "pageWordId": "whyUse-2-desc-4", "matchType": "matched" },
    { "audioWord": "and", "start": 13.68, "end": 14.32, "pageWordId": "whyUse-2-desc-5", "matchType": "matched" },
    { "audioWord": "where", "start": 14.32, "end": 14.56, "pageWordId": "whyUse-2-desc-6", "matchType": "matched" },
    { "audioWord": "mountains", "start": 14.56, "end": 14.96, "pageWordId": "whyUse-2-desc-7", "matchType": "matched" },
    { "audioWord": "are", "start": 14.96, "end": 15.24, "pageWordId": "whyUse-2-desc-8", "matchType": "matched" },
    { "audioWord": "located.", "start": 15.24, "end": 15.68, "pageWordId": "whyUse-2-desc-9", "matchType": "matched" },

    { "audioWord": "The", "start": 16.4, "end": 16.6, "pageWordId": "funFact-1", "matchType": "matched" },
    { "audioWord": "Himalayas", "start": 16.6, "end": 17.2, "pageWordId": "funFact-2", "matchType": "matched" },
    { "audioWord": "are", "start": 17.2, "end": 17.52, "pageWordId": "funFact-3", "matchType": "matched" },
    { "audioWord": "coloured", "start": 17.52, "end": 17.86, "pageWordId": "funFact-4", "matchType": "matched" },
    { "audioWord": "dark", "start": 17.86, "end": 18.32, "pageWordId": "funFact-5", "matchType": "matched" },
    { "audioWord": "brown", "start": 18.32, "end": 18.64, "pageWordId": "funFact-6", "matchType": "matched" },
    { "audioWord": "on", "start": 18.64, "end": 19.24, "pageWordId": "funFact-7", "matchType": "matched" },
    { "audioWord": "physical", "start": 19.24, "end": 19.64, "pageWordId": "funFact-8", "matchType": "matched" },
    { "audioWord": "maps", "start": 19.64, "end": 20.06, "pageWordId": "funFact-9", "matchType": "matched" },
    { "audioWord": "because", "start": 20.06, "end": 20.76, "pageWordId": "funFact-10", "matchType": "matched" },
    { "audioWord": "they", "start": 20.76, "end": 21.12, "pageWordId": "funFact-11", "matchType": "matched" },
    { "audioWord": "are", "start": 21.12, "end": 21.22, "pageWordId": "funFact-12", "matchType": "matched" },
    { "audioWord": "some", "start": 21.22, "end": 21.46, "pageWordId": "funFact-13", "matchType": "matched" },
    { "audioWord": "of", "start": 21.46, "end": 21.62, "pageWordId": "funFact-14", "matchType": "matched" },
    { "audioWord": "the", "start": 21.62, "end": 21.74, "pageWordId": "funFact-15", "matchType": "matched" },
    { "audioWord": "tallest", "start": 21.74, "end": 22.1, "pageWordId": "funFact-16", "matchType": "matched" },
    { "audioWord": "mountains", "start": 22.1, "end": 22.54, "pageWordId": "funFact-17", "matchType": "matched" },
    { "audioWord": "in", "start": 22.54, "end": 22.76, "pageWordId": "funFact-18", "matchType": "matched" },
    { "audioWord": "the", "start": 22.76, "end": 22.94, "pageWordId": "funFact-19", "matchType": "matched" },
    { "audioWord": "world.", "start": 22.94, "end": 23.1, "pageWordId": "funFact-20", "matchType": "matched" }
];
