export const PAGE17_TRANSCRIPT = [
    { "audioWord": "Thematic", "start": 0.0, "end": 0.6, "pageWordId": "title-1", "matchType": "matched" },
    { "audioWord": "maps", "start": 0.6, "end": 1.0, "pageWordId": "title-2", "matchType": "matched" },

    { "audioWord": "maps", "start": 1.52, "end": 1.9, "pageWordId": "subtitle-1", "matchType": "matched" },
    { "audioWord": "that", "start": 1.9, "end": 2.32, "pageWordId": "subtitle-2", "matchType": "matched" },
    { "audioWord": "focus", "start": 2.32, "end": 2.62, "pageWordId": "subtitle-3", "matchType": "matched" },
    { "audioWord": "on", "start": 2.62, "end": 2.9, "pageWordId": "subtitle-4", "matchType": "matched" },
    { "audioWord": "one", "start": 2.9, "end": 3.1, "pageWordId": "subtitle-5", "matchType": "matched" },
    { "audioWord": "special", "start": 3.1, "end": 3.56, "pageWordId": "subtitle-6", "matchType": "matched" },
    { "audioWord": "topic,", "start": 3.56, "end": 3.92, "pageWordId": "subtitle-7", "matchType": "matched" },
    { "audioWord": "like", "start": 4.36, "end": 4.68, "pageWordId": "subtitle-8", "matchType": "matched" },
    { "audioWord": "soil,", "start": 4.68, "end": 5.08, "pageWordId": "subtitle-9", "matchType": "matched" },
    { "audioWord": "rainfall", "start": 5.52, "end": 5.94, "pageWordId": "subtitle-10", "matchType": "matched" },
    { "audioWord": "or", "start": 5.94, "end": 6.4, "pageWordId": "subtitle-11", "matchType": "matched" },
    { "audioWord": "crops.", "start": 6.4, "end": 6.82, "pageWordId": "subtitle-12", "matchType": "matched" },

    { "audioWord": "What", "start": 7.48, "end": 7.62, "pageWordId": "whatIsTitle-1", "matchType": "matched" },
    { "audioWord": "is", "start": 7.62, "end": 7.86, "pageWordId": "whatIsTitle-2", "matchType": "matched" },
    { "audioWord": "a", "start": 7.86, "end": 7.96, "pageWordId": "whatIsTitle-3", "matchType": "matched" },
    { "audioWord": "thematic", "start": 7.96, "end": 8.38, "pageWordId": "whatIsTitle-4", "matchType": "matched" },
    { "audioWord": "map?", "start": 8.38, "end": 8.6, "pageWordId": "whatIsTitle-5", "matchType": "matched" },

    { "audioWord": "A", "start": 9.28, "end": 9.5, "pageWordId": "whatIs-0-1", "matchType": "matched" },
    { "audioWord": "thematic", "start": 9.5, "end": 9.94, "pageWordId": "whatIs-0-2", "matchType": "matched" },
    { "audioWord": "map", "start": 9.94, "end": 10.36, "pageWordId": "whatIs-0-3", "matchType": "matched" },
    { "audioWord": "focuses", "start": 10.36, "end": 10.96, "pageWordId": "whatIs-0-4", "matchType": "matched" },
    { "audioWord": "on", "start": 10.96, "end": 11.4, "pageWordId": "whatIs-0-5", "matchType": "matched" },
    { "audioWord": "one", "start": 11.4, "end": 11.7, "pageWordId": "whatIs-0-6", "matchType": "matched" },
    { "audioWord": "special", "start": 11.7, "end": 12.12, "pageWordId": "whatIs-0-7", "matchType": "matched" },
    { "audioWord": "topic", "start": 12.12, "end": 12.5, "pageWordId": "whatIs-0-8", "matchType": "matched" },
    { "audioWord": "or", "start": 12.5, "end": 12.82, "pageWordId": "whatIs-0-9", "matchType": "matched" },
    { "audioWord": "theme.", "start": 12.82, "end": 13.08, "pageWordId": "whatIs-0-10", "matchType": "matched" },

    { "audioWord": "Instead", "start": 13.62, "end": 13.94, "pageWordId": "whatIs-1-1", "matchType": "matched" },
    { "audioWord": "of", "start": 13.94, "end": 14.2, "pageWordId": "whatIs-1-2", "matchType": "matched" },
    { "audioWord": "showing", "start": 14.2, "end": 14.44, "pageWordId": "whatIs-1-3", "matchType": "matched" },
    { "audioWord": "borders,", "start": 14.44, "end": 14.92, "pageWordId": "whatIs-1-4", "matchType": "matched" },
    { "audioWord": "it", "start": 15.36, "end": 15.58, "pageWordId": "whatIs-1-5", "matchType": "matched" },
    { "audioWord": "shows", "start": 15.58, "end": 15.86, "pageWordId": "whatIs-1-6", "matchType": "matched" },
    { "audioWord": "specific", "start": 15.86, "end": 16.4, "pageWordId": "whatIs-1-7", "matchType": "matched" },
    { "audioWord": "information", "start": 16.4, "end": 17.02, "pageWordId": "whatIs-1-8", "matchType": "matched" },
    { "audioWord": "like", "start": 17.02, "end": 17.32, "pageWordId": "whatIs-1-9", "matchType": "matched" },
    { "audioWord": "rainfall,", "start": 17.32, "end": 17.86, "pageWordId": "whatIs-1-10", "matchType": "matched" },
    { "audioWord": "types", "start": 18.34, "end": 18.64, "pageWordId": "whatIs-1-11", "matchType": "matched" },
    { "audioWord": "of", "start": 18.64, "end": 18.92, "pageWordId": "whatIs-1-12", "matchType": "matched" },
    { "audioWord": "crops,", "start": 18.92, "end": 19.24, "pageWordId": "whatIs-1-13", "matchType": "matched" },
    { "audioWord": "or", "start": 19.24, "end": 19.76, "pageWordId": "whatIs-1-14", "matchType": "matched" },
    { "audioWord": "soil.", "start": 19.76, "end": 20.14, "pageWordId": "whatIs-1-15", "matchType": "matched" },

    { "audioWord": "What", "start": 20.5, "end": 20.72, "pageWordId": "featuresTitle-1", "matchType": "matched" },
    { "audioWord": "can", "start": 20.72, "end": 20.96, "pageWordId": "featuresTitle-2", "matchType": "matched" },
    { "audioWord": "we", "start": 20.96, "end": 21.18, "pageWordId": "featuresTitle-3", "matchType": "matched" },
    { "audioWord": "learn", "start": 21.18, "end": 21.42, "pageWordId": "featuresTitle-4", "matchType": "matched" },
    { "audioWord": "from", "start": 21.42, "end": 21.78, "pageWordId": "featuresTitle-5", "matchType": "matched" },
    { "audioWord": "thematic", "start": 21.78, "end": 22.34, "pageWordId": "featuresTitle-6", "matchType": "matched" },
    { "audioWord": "maps?", "start": 22.34, "end": 22.74, "pageWordId": "featuresTitle-7", "matchType": "matched" },

    { "audioWord": "Soil", "start": 24.04, "end": 24.6, "pageWordId": "feature-0-title-1", "matchType": "matched" },
    { "audioWord": "types", "start": 24.6, "end": 25.02, "pageWordId": "feature-0-title-2", "matchType": "matched" },

    { "audioWord": "show", "start": 25.02, "end": 25.5, "pageWordId": "feature-0-desc-1", "matchType": "matched" },
    { "audioWord": "where", "start": 25.5, "end": 25.94, "pageWordId": "feature-0-desc-2", "matchType": "matched" },
    { "audioWord": "different", "start": 25.94, "end": 26.28, "pageWordId": "feature-0-desc-3", "matchType": "matched" },
    { "audioWord": "kinds", "start": 26.28, "end": 26.56, "pageWordId": "feature-0-desc-4", "matchType": "matched" },
    { "audioWord": "of", "start": 26.56, "end": 26.84, "pageWordId": "feature-0-desc-5", "matchType": "matched" },
    { "audioWord": "soil", "start": 26.84, "end": 27.02, "pageWordId": "feature-0-desc-6", "matchType": "matched" },
    { "audioWord": "are", "start": 27.02, "end": 27.28, "pageWordId": "feature-0-desc-7", "matchType": "matched" },
    { "audioWord": "found", "start": 27.28, "end": 27.56, "pageWordId": "feature-0-desc-8", "matchType": "matched" },
    { "audioWord": "for", "start": 27.56, "end": 27.82, "pageWordId": "feature-0-desc-9", "matchType": "matched" },
    { "audioWord": "farming.", "start": 27.82, "end": 28.1, "pageWordId": "feature-0-desc-10", "matchType": "matched" }
];
