export const PAGE20_TRANSCRIPT = [
    { "audioWord": "Why", "start": 0.0, "end": 0.3, "pageWordId": "whyUseTitle-1", "matchType": "matched" },
    { "audioWord": "do", "start": 0.3, "end": 0.52, "pageWordId": "whyUseTitle-2", "matchType": "matched" },
    { "audioWord": "we", "start": 0.52, "end": 0.74, "pageWordId": "whyUseTitle-3", "matchType": "matched" },
    { "audioWord": "use", "start": 0.74, "end": 1.04, "pageWordId": "whyUseTitle-4", "matchType": "matched" },
    { "audioWord": "thematic", "start": 1.04, "end": 1.56, "pageWordId": "whyUseTitle-5", "matchType": "matched" },
    { "audioWord": "maps?", "start": 1.56, "end": 1.9, "pageWordId": "whyUseTitle-6", "matchType": "matched" },

    { "audioWord": "find", "start": 4.06, "end": 4.34, "pageWordId": "whyUse-0-desc-1", "matchType": "matched" },
    { "audioWord": "the", "start": 4.34, "end": 4.66, "pageWordId": "whyUse-0-desc-2", "matchType": "matched" },
    { "audioWord": "best", "start": 4.66, "end": 4.84, "pageWordId": "whyUse-0-desc-3", "matchType": "matched" },
    { "audioWord": "places", "start": 4.84, "end": 5.2, "pageWordId": "whyUse-0-desc-4", "matchType": "matched" },
    { "audioWord": "to", "start": 5.2, "end": 5.48, "pageWordId": "whyUse-0-desc-5", "matchType": "matched" },
    { "audioWord": "grow", "start": 5.48, "end": 5.66, "pageWordId": "whyUse-0-desc-6", "matchType": "matched" },
    { "audioWord": "different", "start": 5.66, "end": 6.04, "pageWordId": "whyUse-0-desc-7", "matchType": "matched" },
    { "audioWord": "crops.", "start": 6.04, "end": 6.4, "pageWordId": "whyUse-0-desc-8", "matchType": "matched" },

    { "audioWord": "know", "start": 7.96, "end": 8.3, "pageWordId": "whyUse-1-desc-1", "matchType": "matched" },
    { "audioWord": "where", "start": 8.3, "end": 8.88, "pageWordId": "whyUse-1-desc-2", "matchType": "matched" },
    { "audioWord": "it", "start": 8.88, "end": 9.08, "pageWordId": "whyUse-1-desc-3", "matchType": "matched" },
    { "audioWord": "will", "start": 9.08, "end": 9.3, "pageWordId": "whyUse-1-desc-4", "matchType": "matched" },
    { "audioWord": "rain", "start": 9.3, "end": 9.5, "pageWordId": "whyUse-1-desc-5", "matchType": "matched" },
    { "audioWord": "the", "start": 9.5, "end": 9.72, "pageWordId": "whyUse-1-desc-6", "matchType": "matched" },
    { "audioWord": "most", "start": 9.72, "end": 10.04, "pageWordId": "whyUse-1-desc-7", "matchType": "matched" },
    { "audioWord": "during", "start": 10.04, "end": 10.42, "pageWordId": "whyUse-1-desc-8", "matchType": "matched" },
    { "audioWord": "the", "start": 10.42, "end": 10.62, "pageWordId": "whyUse-1-desc-9", "matchType": "matched" },
    { "audioWord": "year.", "start": 10.62, "end": 10.82, "pageWordId": "whyUse-1-desc-10", "matchType": "matched" },

    { "audioWord": "see", "start": 12.7, "end": 12.86, "pageWordId": "whyUse-2-desc-1", "matchType": "matched" },
    { "audioWord": "where", "start": 12.86, "end": 13.1, "pageWordId": "whyUse-2-desc-2", "matchType": "matched" },
    { "audioWord": "people", "start": 13.1, "end": 13.48, "pageWordId": "whyUse-2-desc-3", "matchType": "matched" },
    { "audioWord": "live", "start": 13.48, "end": 13.76, "pageWordId": "whyUse-2-desc-4", "matchType": "matched" },
    { "audioWord": "and", "start": 13.76, "end": 14.42, "pageWordId": "whyUse-2-desc-5", "matchType": "matched" },
    { "audioWord": "where", "start": 14.42, "end": 14.7, "pageWordId": "whyUse-2-desc-6", "matchType": "matched" },
    { "audioWord": "natural", "start": 14.7, "end": 15.14, "pageWordId": "whyUse-2-desc-7", "matchType": "matched" },
    { "audioWord": "resources", "start": 15.14, "end": 15.66, "pageWordId": "whyUse-2-desc-8", "matchType": "matched" },
    { "audioWord": "are", "start": 15.66, "end": 15.96, "pageWordId": "whyUse-2-desc-9", "matchType": "matched" },
    { "audioWord": "found.", "start": 15.96, "end": 16.24, "pageWordId": "whyUse-2-desc-10", "matchType": "matched" },

    { "audioWord": "A", "start": 17.08, "end": 17.36, "pageWordId": "funFact-1", "matchType": "matched" },
    { "audioWord": "soil", "start": 17.36, "end": 17.58, "pageWordId": "funFact-2", "matchType": "matched" },
    { "audioWord": "map", "start": 17.58, "end": 17.82, "pageWordId": "funFact-3", "matchType": "matched" },
    { "audioWord": "and", "start": 17.82, "end": 18.18, "pageWordId": "funFact-4", "matchType": "matched" },
    { "audioWord": "a", "start": 18.18, "end": 18.34, "pageWordId": "funFact-5", "matchType": "matched" },
    { "audioWord": "rainfall", "start": 18.34, "end": 18.68, "pageWordId": "funFact-6", "matchType": "matched" },
    { "audioWord": "map", "start": 18.68, "end": 18.94, "pageWordId": "funFact-7", "matchType": "matched" },
    { "audioWord": "of", "start": 18.94, "end": 19.12, "pageWordId": "funFact-8", "matchType": "matched" },
    { "audioWord": "India", "start": 19.12, "end": 19.56, "pageWordId": "funFact-9", "matchType": "matched" },
    { "audioWord": "cover", "start": 19.56, "end": 20.16, "pageWordId": "funFact-10", "matchType": "matched" },
    { "audioWord": "the", "start": 20.16, "end": 20.54, "pageWordId": "funFact-11", "matchType": "matched" },
    { "audioWord": "exact", "start": 20.54, "end": 20.9, "pageWordId": "funFact-12", "matchType": "matched" },
    { "audioWord": "same", "start": 20.9, "end": 21.14, "pageWordId": "funFact-13", "matchType": "matched" },
    { "audioWord": "land,", "start": 21.14, "end": 21.44, "pageWordId": "funFact-14", "matchType": "matched" },
    { "audioWord": "but", "start": 21.72, "end": 22.04, "pageWordId": "funFact-15", "matchType": "matched" },
    { "audioWord": "they", "start": 22.04, "end": 22.3, "pageWordId": "funFact-16", "matchType": "matched" },
    { "audioWord": "tell", "start": 22.3, "end": 22.46, "pageWordId": "funFact-17", "matchType": "matched" },
    { "audioWord": "us", "start": 22.46, "end": 22.96, "pageWordId": "funFact-18", "matchType": "matched" },
    { "audioWord": "two", "start": 22.96, "end": 23.26, "pageWordId": "funFact-19", "matchType": "matched" },
    { "audioWord": "completely", "start": 23.26, "end": 23.84, "pageWordId": "funFact-20", "matchType": "matched" },
    { "audioWord": "different", "start": 23.84, "end": 24.26, "pageWordId": "funFact-21", "matchType": "matched" },
    { "audioWord": "stories.", "start": 24.26, "end": 24.72, "pageWordId": "funFact-22", "matchType": "matched" }
];
