export const PAGE16_TRANSCRIPT = [
    { "audioWord": "Why", "start": 0.0, "end": 0.36, "pageWordId": "whyUseTitle-1", "matchType": "matched" },
    { "audioWord": "do", "start": 0.36, "end": 0.56, "pageWordId": "whyUseTitle-2", "matchType": "matched" },
    { "audioWord": "we", "start": 0.56, "end": 0.78, "pageWordId": "whyUseTitle-3", "matchType": "matched" },
    { "audioWord": "use", "start": 0.78, "end": 1.06, "pageWordId": "whyUseTitle-4", "matchType": "matched" },
    { "audioWord": "political", "start": 1.06, "end": 1.54, "pageWordId": "whyUseTitle-5", "matchType": "matched" },
    { "audioWord": "maps?", "start": 1.54, "end": 1.9, "pageWordId": "whyUseTitle-6", "matchType": "matched" },

    { "audioWord": "learn", "start": 4.06, "end": 4.26, "pageWordId": "whyUse-0-desc-1", "matchType": "matched" },
    { "audioWord": "about", "start": 4.26, "end": 4.6, "pageWordId": "whyUse-0-desc-2", "matchType": "matched" },
    { "audioWord": "the", "start": 4.6, "end": 4.82, "pageWordId": "whyUse-0-desc-3", "matchType": "matched" },
    { "audioWord": "different", "start": 4.82, "end": 5.04, "pageWordId": "whyUse-0-desc-4", "matchType": "matched" },
    { "audioWord": "countries", "start": 5.04, "end": 5.52, "pageWordId": "whyUse-0-desc-5", "matchType": "matched" },
    { "audioWord": "and", "start": 5.52, "end": 5.84, "pageWordId": "whyUse-0-desc-6", "matchType": "matched" },
    { "audioWord": "states", "start": 5.84, "end": 6.14, "pageWordId": "whyUse-0-desc-7", "matchType": "matched" },
    { "audioWord": "in", "start": 6.14, "end": 6.32, "pageWordId": "whyUse-0-desc-8", "matchType": "matched" },
    { "audioWord": "the", "start": 6.32, "end": 6.48, "pageWordId": "whyUse-0-desc-9", "matchType": "matched" },
    { "audioWord": "world.", "start": 6.48, "end": 6.74, "pageWordId": "whyUse-0-desc-10", "matchType": "matched" },

    { "audioWord": "find", "start": 8.26, "end": 8.5, "pageWordId": "whyUse-1-desc-1", "matchType": "matched" },
    { "audioWord": "out", "start": 8.5, "end": 8.9, "pageWordId": "whyUse-1-desc-2", "matchType": "matched" },
    { "audioWord": "which", "start": 8.9, "end": 9.32, "pageWordId": "whyUse-1-desc-3", "matchType": "matched" },
    { "audioWord": "state", "start": 9.32, "end": 9.7, "pageWordId": "whyUse-1-desc-4", "matchType": "matched" },
    { "audioWord": "a", "start": 9.7, "end": 10.02, "pageWordId": "whyUse-1-desc-5", "matchType": "matched" },
    { "audioWord": "city", "start": 10.02, "end": 10.22, "pageWordId": "whyUse-1-desc-6", "matchType": "matched" },
    { "audioWord": "belongs", "start": 10.22, "end": 10.64, "pageWordId": "whyUse-1-desc-7", "matchType": "matched" },
    { "audioWord": "to", "start": 10.64, "end": 10.88, "pageWordId": "whyUse-1-desc-8", "matchType": "matched" },
    { "audioWord": "when", "start": 10.88, "end": 11.08, "pageWordId": "whyUse-1-desc-9", "matchType": "matched" },
    { "audioWord": "travelling.", "start": 11.08, "end": 11.44, "pageWordId": "whyUse-1-desc-10", "matchType": "matched" },

    { "audioWord": "see", "start": 13.2, "end": 13.4, "pageWordId": "whyUse-2-desc-1", "matchType": "matched" },
    { "audioWord": "the", "start": 13.4, "end": 13.6, "pageWordId": "whyUse-2-desc-2", "matchType": "matched" },
    { "audioWord": "borders", "start": 13.6, "end": 13.92, "pageWordId": "whyUse-2-desc-3", "matchType": "matched" },
    { "audioWord": "that", "start": 13.92, "end": 14.6, "pageWordId": "whyUse-2-desc-4", "matchType": "matched" },
    { "audioWord": "separate", "start": 14.6, "end": 15.02, "pageWordId": "whyUse-2-desc-5", "matchType": "matched" },
    { "audioWord": "different", "start": 15.02, "end": 15.44, "pageWordId": "whyUse-2-desc-6", "matchType": "matched" },
    { "audioWord": "nations.", "start": 15.44, "end": 15.9, "pageWordId": "whyUse-2-desc-7", "matchType": "matched" },

    { "audioWord": "India", "start": 16.6, "end": 16.86, "pageWordId": "funFact-1", "matchType": "matched" },
    { "audioWord": "currently", "start": 16.86, "end": 17.36, "pageWordId": "funFact-2", "matchType": "matched" },
    { "audioWord": "has", "start": 17.36, "end": 17.76, "pageWordId": "funFact-3", "matchType": "matched" },
    { "audioWord": "28", "start": 17.76, "end": 18.28, "pageWordId": "funFact-4", "matchType": "matched" },
    { "audioWord": "states", "start": 18.28, "end": 18.74, "pageWordId": "funFact-5", "matchType": "matched" },
    { "audioWord": "and", "start": 18.74, "end": 19.34, "pageWordId": "funFact-6", "matchType": "matched" },
    { "audioWord": "8", "start": 19.34, "end": 19.7, "pageWordId": "funFact-7", "matchType": "matched" },
    { "audioWord": "union", "start": 19.7, "end": 20.04, "pageWordId": "funFact-8", "matchType": "matched" },
    { "audioWord": "territories,", "start": 20.04, "end": 20.66, "pageWordId": "funFact-9", "matchType": "matched" },
    { "audioWord": "each", "start": 21.12, "end": 21.44, "pageWordId": "funFact-10", "matchType": "matched" },
    { "audioWord": "with", "start": 21.44, "end": 21.68, "pageWordId": "funFact-11", "matchType": "matched" },
    { "audioWord": "its", "start": 21.68, "end": 21.86, "pageWordId": "funFact-12", "matchType": "matched" },
    { "audioWord": "own", "start": 21.86, "end": 22.1, "pageWordId": "funFact-13", "matchType": "matched" },
    { "audioWord": "borders", "start": 22.1, "end": 22.44, "pageWordId": "funFact-14", "matchType": "matched" },
    { "audioWord": "on", "start": 22.48, "end": 22.64, "pageWordId": "funFact-15", "matchType": "matched" },
    { "audioWord": "the", "start": 22.64, "end": 22.84, "pageWordId": "funFact-16", "matchType": "matched" },
    { "audioWord": "map.", "start": 22.84, "end": 22.96, "pageWordId": "funFact-17", "matchType": "matched" }
];
