export const PAGE19_TRANSCRIPT = [
    { "audioWord": "Colours", "start": 0.0, "end": 0.66, "pageWordId": "colorsTitle-1", "matchType": "matched" },
    { "audioWord": "and", "start": 0.66, "end": 1.02, "pageWordId": "colorsTitle-2", "matchType": "matched" },
    { "audioWord": "legends.", "start": 1.02, "end": 1.38, "pageWordId": "colorsTitle-3", "matchType": "matched" },

    { "audioWord": "The", "start": 2.2, "end": 2.34, "pageWordId": "color-0-desc-1", "matchType": "matched" },
    { "audioWord": "legend", "start": 2.34, "end": 2.6, "pageWordId": "color-0-desc-2", "matchType": "matched" },
    { "audioWord": "box", "start": 2.6, "end": 2.92, "pageWordId": "color-0-desc-3", "matchType": "matched" },
    { "audioWord": "explains", "start": 2.92, "end": 3.54, "pageWordId": "color-0-desc-4", "matchType": "matched" },
    { "audioWord": "what", "start": 3.54, "end": 3.86, "pageWordId": "color-0-desc-5", "matchType": "matched" },
    { "audioWord": "each", "start": 3.86, "end": 4.14, "pageWordId": "color-0-desc-6", "matchType": "matched" },
    { "audioWord": "colour", "start": 4.14, "end": 4.38, "pageWordId": "color-0-desc-7", "matchType": "matched" },
    { "audioWord": "or", "start": 4.38, "end": 4.76, "pageWordId": "color-0-desc-8", "matchType": "matched" },
    { "audioWord": "pattern", "start": 4.76, "end": 5.18, "pageWordId": "color-0-desc-9", "matchType": "matched" },
    { "audioWord": "means", "start": 5.18, "end": 5.66, "pageWordId": "color-0-desc-10", "matchType": "matched" },
    { "audioWord": "on", "start": 5.66, "end": 5.98, "pageWordId": "color-0-desc-11", "matchType": "matched" },
    { "audioWord": "the", "start": 5.98, "end": 6.12, "pageWordId": "color-0-desc-12", "matchType": "matched" },
    { "audioWord": "map.", "start": 6.12, "end": 6.4, "pageWordId": "color-0-desc-13", "matchType": "matched" },

    { "audioWord": "Light", "start": 7.12, "end": 7.32, "pageWordId": "color-1-desc-1", "matchType": "matched" },
    { "audioWord": "green", "start": 7.32, "end": 7.62, "pageWordId": "color-1-desc-2", "matchType": "matched" },
    { "audioWord": "shows", "start": 7.62, "end": 7.94, "pageWordId": "color-1-desc-3", "matchType": "matched" },
    { "audioWord": "good", "start": 7.94, "end": 8.24, "pageWordId": "color-1-desc-4", "matchType": "matched" },
    { "audioWord": "soil", "start": 8.24, "end": 8.58, "pageWordId": "color-1-desc-5", "matchType": "matched" },
    { "audioWord": "for", "start": 8.58, "end": 8.84, "pageWordId": "color-1-desc-6", "matchType": "matched" },
    { "audioWord": "farming", "start": 8.84, "end": 9.18, "pageWordId": "color-1-desc-7", "matchType": "matched" },
    { "audioWord": "near", "start": 9.18, "end": 9.46, "pageWordId": "color-1-desc-8", "matchType": "matched" },
    { "audioWord": "rivers.", "start": 9.46, "end": 9.88, "pageWordId": "color-1-desc-9", "matchType": "matched" },

    { "audioWord": "Dark", "start": 10.54, "end": 10.8, "pageWordId": "color-2-desc-1", "matchType": "matched" },
    { "audioWord": "grey", "start": 10.8, "end": 11.12, "pageWordId": "color-2-desc-2", "matchType": "matched" },
    { "audioWord": "shows", "start": 11.12, "end": 11.5, "pageWordId": "color-2-desc-3", "matchType": "matched" },
    { "audioWord": "black", "start": 11.5, "end": 11.84, "pageWordId": "color-2-desc-4", "matchType": "matched" },
    { "audioWord": "soil", "start": 11.84, "end": 12.26, "pageWordId": "color-2-desc-5", "matchType": "matched" },
    { "audioWord": "that", "start": 12.26, "end": 12.74, "pageWordId": "color-2-desc-6", "matchType": "matched" },
    { "audioWord": "is", "start": 12.74, "end": 12.94, "pageWordId": "color-2-desc-7", "matchType": "matched" },
    { "audioWord": "great", "start": 12.94, "end": 13.18, "pageWordId": "color-2-desc-8", "matchType": "matched" },
    { "audioWord": "for", "start": 13.18, "end": 13.42, "pageWordId": "color-2-desc-9", "matchType": "matched" },
    { "audioWord": "growing", "start": 13.42, "end": 13.74, "pageWordId": "color-2-desc-10", "matchType": "matched" },
    { "audioWord": "cotton.", "start": 13.74, "end": 14.18, "pageWordId": "color-2-desc-11", "matchType": "matched" },

    { "audioWord": "Red", "start": 14.82, "end": 15.04, "pageWordId": "color-3-desc-1", "matchType": "matched" },
    { "audioWord": "and", "start": 15.04, "end": 15.18, "pageWordId": "color-3-desc-2", "matchType": "matched" },
    { "audioWord": "yellow", "start": 15.18, "end": 15.44, "pageWordId": "color-3-desc-3", "matchType": "matched" },
    { "audioWord": "colours", "start": 15.44, "end": 15.94, "pageWordId": "color-3-desc-4", "matchType": "matched" },
    { "audioWord": "show", "start": 15.94, "end": 16.4, "pageWordId": "color-3-desc-5", "matchType": "matched" },
    { "audioWord": "older", "start": 16.4, "end": 16.94, "pageWordId": "color-3-desc-6", "matchType": "matched" },
    { "audioWord": "rocky", "start": 16.94, "end": 17.36, "pageWordId": "color-3-desc-7", "matchType": "matched" },
    { "audioWord": "soils.", "start": 17.36, "end": 17.74, "pageWordId": "color-3-desc-8", "matchType": "matched" }
];
