export const PAGE12_TRANSCRIPT = [
    { "audioWord": "political", "start": 7.2, "end": 7.62, "pageWordId": "title-1", "matchType": "matched" },
    { "audioWord": "maps.", "start": 7.62, "end": 8.1, "pageWordId": "title-2", "matchType": "matched" },

    { "audioWord": "Political", "start": 8.7, "end": 9.06, "pageWordId": "subtitle-1", "matchType": "matched" },
    { "audioWord": "maps", "start": 9.06, "end": 9.5, "pageWordId": "subtitle-2", "matchType": "matched" },
    { "audioWord": "show", "start": 9.5, "end": 9.94, "pageWordId": "subtitle-3", "matchType": "matched" },
    { "audioWord": "countries,", "start": 9.94, "end": 10.5, "pageWordId": "subtitle-4", "matchType": "matched" },
    { "audioWord": "states,", "start": 10.9, "end": 11.32, "pageWordId": "subtitle-5", "matchType": "matched" },
    { "audioWord": "cities", "start": 11.78, "end": 12.04, "pageWordId": "subtitle-6", "matchType": "matched" },
    { "audioWord": "and", "start": 12.04, "end": 12.36, "pageWordId": "subtitle-7", "matchType": "matched" },
    { "audioWord": "their", "start": 12.36, "end": 12.62, "pageWordId": "subtitle-8", "matchType": "matched" },
    { "audioWord": "borders.", "start": 12.62, "end": 13.02, "pageWordId": "subtitle-9", "matchType": "matched" },

    { "audioWord": "what", "start": 13.88, "end": 14.46, "pageWordId": "whatIsTitle-1", "matchType": "matched" },
    { "audioWord": "is", "start": 14.46, "end": 14.66, "pageWordId": "whatIsTitle-2", "matchType": "matched" },
    { "audioWord": "a", "start": 14.66, "end": 14.82, "pageWordId": "whatIsTitle-3", "matchType": "matched" },
    { "audioWord": "political", "start": 14.82, "end": 15.2, "pageWordId": "whatIsTitle-4", "matchType": "matched" },
    { "audioWord": "map?", "start": 15.2, "end": 15.5, "pageWordId": "whatIsTitle-5", "matchType": "matched" },

    { "audioWord": "A", "start": 15.94, "end": 16.18, "pageWordId": "whatIs-0-1", "matchType": "matched" },
    { "audioWord": "political", "start": 16.18, "end": 16.52, "pageWordId": "whatIs-0-2", "matchType": "matched" },
    { "audioWord": "map", "start": 16.52, "end": 16.86, "pageWordId": "whatIs-0-3", "matchType": "matched" },
    { "audioWord": "shows", "start": 16.86, "end": 17.42, "pageWordId": "whatIs-0-4", "matchType": "matched" },
    { "audioWord": "the", "start": 17.42, "end": 17.64, "pageWordId": "whatIs-0-5", "matchType": "matched" },
    { "audioWord": "borders", "start": 17.64, "end": 17.92, "pageWordId": "whatIs-0-6", "matchType": "matched" },
    { "audioWord": "of", "start": 17.92, "end": 18.16, "pageWordId": "whatIs-0-7", "matchType": "matched" },
    { "audioWord": "countries,", "start": 18.16, "end": 18.66, "pageWordId": "whatIs-0-8", "matchType": "matched" },
    { "audioWord": "states,", "start": 18.9, "end": 19.26, "pageWordId": "whatIs-0-9", "matchType": "matched" },
    { "audioWord": "and", "start": 19.26, "end": 19.56, "pageWordId": "whatIs-0-10", "matchType": "matched" },
    { "audioWord": "cities.", "start": 19.56, "end": 20.04, "pageWordId": "whatIs-0-11", "matchType": "matched" },

    { "audioWord": "It", "start": 20.54, "end": 20.78, "pageWordId": "whatIs-1-1", "matchType": "matched" },
    { "audioWord": "helps", "start": 20.78, "end": 21.06, "pageWordId": "whatIs-1-2", "matchType": "matched" },
    { "audioWord": "us", "start": 21.06, "end": 21.32, "pageWordId": "whatIs-1-3", "matchType": "matched" },
    { "audioWord": "see", "start": 21.32, "end": 21.58, "pageWordId": "whatIs-1-4", "matchType": "matched" },
    { "audioWord": "the", "start": 21.58, "end": 21.84, "pageWordId": "whatIs-1-5", "matchType": "matched" },
    { "audioWord": "different", "start": 21.84, "end": 22.1, "pageWordId": "whatIs-1-6", "matchType": "matched" },
    { "audioWord": "regions", "start": 22.1, "end": 22.5, "pageWordId": "whatIs-1-7", "matchType": "matched" },
    { "audioWord": "and", "start": 22.5, "end": 22.76, "pageWordId": "whatIs-1-8", "matchType": "matched" },
    { "audioWord": "governments", "start": 22.76, "end": 23.22, "pageWordId": "whatIs-1-9", "matchType": "matched" },
    { "audioWord": "created", "start": 23.22, "end": 23.78, "pageWordId": "whatIs-1-10", "matchType": "matched" },
    { "audioWord": "by", "start": 23.78, "end": 24.12, "pageWordId": "whatIs-1-11", "matchType": "matched" },
    { "audioWord": "people.", "start": 24.12, "end": 24.54, "pageWordId": "whatIs-1-12", "matchType": "matched" },

    { "audioWord": "What", "start": 25.48, "end": 25.66, "pageWordId": "featuresTitle-1", "matchType": "matched" },
    { "audioWord": "can", "start": 25.66, "end": 25.92, "pageWordId": "featuresTitle-2", "matchType": "matched" },
    { "audioWord": "we", "start": 25.92, "end": 26.18, "pageWordId": "featuresTitle-3", "matchType": "matched" },
    { "audioWord": "see?", "start": 26.18, "end": 26.44, "pageWordId": "featuresTitle-4", "matchType": "matched" },

    { "audioWord": "Countries", "start": 27.12, "end": 27.74, "pageWordId": "feature-0-title-1", "matchType": "matched" },
    { "audioWord": "different", "start": 27.96, "end": 28.24, "pageWordId": "feature-0-desc-1", "matchType": "matched" },
    { "audioWord": "nations", "start": 28.24, "end": 28.64, "pageWordId": "feature-0-desc-2", "matchType": "matched" },
    { "audioWord": "around", "start": 28.64, "end": 28.98, "pageWordId": "feature-0-desc-3", "matchType": "matched" },
    { "audioWord": "the", "start": 28.98, "end": 29.2, "pageWordId": "feature-0-desc-4", "matchType": "matched" },
    { "audioWord": "world", "start": 29.2, "end": 29.48, "pageWordId": "feature-0-desc-5", "matchType": "matched" },
    { "audioWord": "with", "start": 29.48, "end": 29.88, "pageWordId": "feature-0-desc-6", "matchType": "matched" },
    { "audioWord": "their", "start": 29.88, "end": 30.14, "pageWordId": "feature-0-desc-7", "matchType": "matched" },
    { "audioWord": "own", "start": 30.14, "end": 30.4, "pageWordId": "feature-0-desc-8", "matchType": "matched" },
    { "audioWord": "governments.", "start": 30.4, "end": 30.76, "pageWordId": "feature-0-desc-9", "matchType": "matched" }
];
