export const PAGE7_TRANSCRIPT = [
    { "audioWord": "Physical", "start": 0.0, "end": 0.56, "pageWordId": "title-1", "matchType": "matched" },
    { "audioWord": "maps,", "start": 0.56, "end": 1.0, "pageWordId": "title-2", "matchType": "matched" },
    
    { "audioWord": "maps", "start": 1.44, "end": 1.8, "pageWordId": "subtitle-1", "matchType": "matched" },
    { "audioWord": "that", "start": 1.8, "end": 2.34, "pageWordId": "subtitle-2", "matchType": "matched" },
    { "audioWord": "show", "start": 2.34, "end": 2.66, "pageWordId": "subtitle-3", "matchType": "matched" },
    { "audioWord": "Earth's", "start": 2.66, "end": 3.24, "pageWordId": "subtitle-4", "matchType": "matched" },
    { "audioWord": "natural", "start": 3.24, "end": 3.5, "pageWordId": "subtitle-5", "matchType": "matched" },
    { "audioWord": "features,", "start": 3.5, "end": 4.0, "pageWordId": "subtitle-6", "matchType": "matched" },
    { "audioWord": "like", "start": 4.54, "end": 4.68, "pageWordId": "subtitle-7", "matchType": "matched" },
    { "audioWord": "mountains", "start": 4.68, "end": 5.1, "pageWordId": "subtitle-8", "matchType": "matched" },
    { "audioWord": "and", "start": 5.1, "end": 5.38, "pageWordId": "subtitle-9", "matchType": "matched" },
    { "audioWord": "rivers.", "start": 5.38, "end": 5.72, "pageWordId": "subtitle-10", "matchType": "matched" },

    { "audioWord": "What", "start": 6.38, "end": 6.54, "pageWordId": "whatIsTitle-1", "matchType": "matched" },
    { "audioWord": "is", "start": 6.54, "end": 6.76, "pageWordId": "whatIsTitle-2", "matchType": "matched" },
    { "audioWord": "a", "start": 6.76, "end": 6.96, "pageWordId": "whatIsTitle-3", "matchType": "matched" },
    { "audioWord": "physical", "start": 6.96, "end": 7.24, "pageWordId": "whatIsTitle-4", "matchType": "matched" },
    { "audioWord": "map?", "start": 7.24, "end": 7.5, "pageWordId": "whatIsTitle-5", "matchType": "matched" },

    { "audioWord": "A", "start": 8.18, "end": 8.34, "pageWordId": "what1-1", "matchType": "matched" },
    { "audioWord": "physical", "start": 8.34, "end": 8.66, "pageWordId": "what1-2", "matchType": "matched" },
    { "audioWord": "map", "start": 8.66, "end": 8.9, "pageWordId": "what1-3", "matchType": "matched" },
    { "audioWord": "shows", "start": 8.9, "end": 9.24, "pageWordId": "what1-4", "matchType": "matched" },
    { "audioWord": "the", "start": 9.24, "end": 9.46, "pageWordId": "what1-5", "matchType": "matched" },
    { "audioWord": "natural", "start": 9.46, "end": 9.82, "pageWordId": "what1-6", "matchType": "matched" },
    { "audioWord": "features", "start": 9.82, "end": 10.2, "pageWordId": "what1-7", "matchType": "matched" },
    { "audioWord": "of", "start": 10.2, "end": 10.46, "pageWordId": "what1-8", "matchType": "matched" },
    { "audioWord": "the", "start": 10.46, "end": 10.62, "pageWordId": "what1-9", "matchType": "matched" },
    { "audioWord": "Earth.", "start": 10.62, "end": 10.82, "pageWordId": "what1-10", "matchType": "matched" },

    { "audioWord": "It", "start": 11.36, "end": 11.54, "pageWordId": "what2-1", "matchType": "matched" },
    { "audioWord": "helps", "start": 11.54, "end": 11.78, "pageWordId": "what2-2", "matchType": "matched" },
    { "audioWord": "us", "start": 11.78, "end": 12.06, "pageWordId": "what2-3", "matchType": "matched" },
    { "audioWord": "see", "start": 12.06, "end": 12.26, "pageWordId": "what2-4", "matchType": "matched" },
    { "audioWord": "the", "start": 12.26, "end": 12.5, "pageWordId": "what2-5", "matchType": "matched" },
    { "audioWord": "shape", "start": 12.5, "end": 12.68, "pageWordId": "what2-6", "matchType": "matched" },
    { "audioWord": "of", "start": 12.68, "end": 12.88, "pageWordId": "what2-7", "matchType": "matched" },
    { "audioWord": "the", "start": 12.88, "end": 13.04, "pageWordId": "what2-8", "matchType": "matched" },
    { "audioWord": "land", "start": 13.04, "end": 13.36, "pageWordId": "what2-9", "matchType": "matched" },
    { "audioWord": "without", "start": 13.36, "end": 13.88, "pageWordId": "what2-10", "matchType": "matched" },
    { "audioWord": "showing", "start": 13.88, "end": 14.3, "pageWordId": "what2-11", "matchType": "matched" },
    { "audioWord": "roads", "start": 14.3, "end": 14.72, "pageWordId": "what2-12", "matchType": "matched" },
    { "audioWord": "or", "start": 14.72, "end": 15.08, "pageWordId": "what2-13", "matchType": "matched" },
    { "audioWord": "cities", "start": 15.08, "end": 15.46, "pageWordId": "what2-14", "matchType": "matched" },
    { "audioWord": "built", "start": 15.46, "end": 15.78, "pageWordId": "what2-15", "matchType": "matched" },
    { "audioWord": "by", "start": 15.78, "end": 16.06, "pageWordId": "what2-16", "matchType": "matched" },
    { "audioWord": "people.", "start": 16.06, "end": 16.34, "pageWordId": "what2-17", "matchType": "matched" }
];
