export const PAGE10_TRANSCRIPT = [
    { "audioWord": "colors", "start": 1.98, "end": 2.2, "pageWordId": "colorsTitle-1", "matchType": "matched" },
    { "audioWord": "used", "start": 2.2, "end": 2.56, "pageWordId": "colorsTitle-2", "matchType": "matched" },
    { "audioWord": "on", "start": 2.56, "end": 2.84, "pageWordId": "colorsTitle-3", "matchType": "matched" },
    { "audioWord": "physical", "start": 2.84, "end": 3.18, "pageWordId": "colorsTitle-4", "matchType": "matched" },
    { "audioWord": "maps.", "start": 3.18, "end": 3.68, "pageWordId": "colorsTitle-5", "matchType": "matched" },

    { "audioWord": "Green", "start": 4.24, "end": 4.5, "pageWordId": "color-0-desc-1", "matchType": "matched" },
    { "audioWord": "represents", "start": 4.5, "end": 5.08, "pageWordId": "color-0-desc-2", "matchType": "matched" },
    { "audioWord": "plains,", "start": 5.08, "end": 5.58, "pageWordId": "color-0-desc-3", "matchType": "matched" },
    { "audioWord": "river", "start": 6.12, "end": 6.3, "pageWordId": "color-0-desc-4", "matchType": "matched" },
    { "audioWord": "valleys", "start": 6.3, "end": 6.64, "pageWordId": "color-0-desc-5", "matchType": "matched" },
    { "audioWord": "and", "start": 6.64, "end": 7.1, "pageWordId": "color-0-desc-6", "matchType": "matched" },
    { "audioWord": "low", "start": 7.1, "end": 7.42, "pageWordId": "color-0-desc-7", "matchType": "matched" },
    { "audioWord": "flatlands.", "start": 7.42, "end": 8.06, "pageWordId": "color-0-desc-8", "matchType": "matched" },
    { "audioWord": "flatlands.", "start": 7.42, "end": 8.06, "pageWordId": "color-0-desc-9", "matchType": "matched" },

    { "audioWord": "Brown", "start": 8.74, "end": 8.98, "pageWordId": "color-1-desc-1", "matchType": "matched" },
    { "audioWord": "is", "start": 8.98, "end": 9.16, "pageWordId": "color-1-desc-2", "matchType": "matched" },
    { "audioWord": "used", "start": 9.16, "end": 9.44, "pageWordId": "color-1-desc-3", "matchType": "matched" },
    { "audioWord": "for", "start": 9.44, "end": 9.7, "pageWordId": "color-1-desc-4", "matchType": "matched" },
    { "audioWord": "high", "start": 9.7, "end": 9.96, "pageWordId": "color-1-desc-5", "matchType": "matched" },
    { "audioWord": "mountains", "start": 9.96, "end": 10.46, "pageWordId": "color-1-desc-6", "matchType": "matched" },
    { "audioWord": "and", "start": 10.46, "end": 10.92, "pageWordId": "color-1-desc-7", "matchType": "matched" },
    { "audioWord": "tall", "start": 10.92, "end": 11.12, "pageWordId": "color-1-desc-8", "matchType": "matched" },
    { "audioWord": "hills.", "start": 11.12, "end": 11.58, "pageWordId": "color-1-desc-9", "matchType": "matched" },

    { "audioWord": "Blue", "start": 12.18, "end": 12.4, "pageWordId": "color-2-desc-1", "matchType": "matched" },
    { "audioWord": "shows", "start": 12.4, "end": 12.74, "pageWordId": "color-2-desc-2", "matchType": "matched" },
    { "audioWord": "water", "start": 12.74, "end": 13.16, "pageWordId": "color-2-desc-3", "matchType": "matched" },
    { "audioWord": "like", "start": 13.16, "end": 13.46, "pageWordId": "color-2-desc-4", "matchType": "matched" },
    { "audioWord": "rivers,", "start": 13.46, "end": 13.94, "pageWordId": "color-2-desc-5", "matchType": "matched" },
    { "audioWord": "lakes,", "start": 14.36, "end": 14.7, "pageWordId": "color-2-desc-6", "matchType": "matched" },
    { "audioWord": "seas", "start": 15.02, "end": 15.3, "pageWordId": "color-2-desc-7", "matchType": "matched" },
    { "audioWord": "and", "start": 15.3, "end": 15.68, "pageWordId": "color-2-desc-8", "matchType": "matched" },
    { "audioWord": "oceans.", "start": 15.68, "end": 16.06, "pageWordId": "color-2-desc-9", "matchType": "matched" },

    { "audioWord": "Yellow", "start": 16.06, "end": 17.0, "pageWordId": "color-3-desc-1", "matchType": "matched" },
    { "audioWord": "is", "start": 17.0, "end": 17.28, "pageWordId": "color-3-desc-2", "matchType": "matched" },
    { "audioWord": "used", "start": 17.28, "end": 17.66, "pageWordId": "color-3-desc-3", "matchType": "matched" },
    { "audioWord": "to", "start": 17.66, "end": 17.96, "pageWordId": "color-3-desc-4", "matchType": "matched" },
    { "audioWord": "show", "start": 17.96, "end": 18.16, "pageWordId": "color-3-desc-5", "matchType": "matched" },
    { "audioWord": "high", "start": 18.16, "end": 18.58, "pageWordId": "color-3-desc-6", "matchType": "matched" },
    { "audioWord": "flatlands", "start": 18.58, "end": 19.18, "pageWordId": "color-3-desc-7", "matchType": "matched" },
    { "audioWord": "flatlands", "start": 18.58, "end": 19.18, "pageWordId": "color-3-desc-8", "matchType": "matched" },
    { "audioWord": "called", "start": 19.18, "end": 19.56, "pageWordId": "color-3-desc-9", "matchType": "matched" },
    { "audioWord": "plateaus.", "start": 19.56, "end": 20.08, "pageWordId": "color-3-desc-10", "matchType": "matched" }
];
