export const PAGE21_TRANSCRIPT = [
    { "audioWord": "Let's", "start": 0.0, "end": 0.44, "pageWordId": "rlabel-1", "matchType": "matched" },
    { "audioWord": "explore.", "start": 0.44, "end": 1.06, "pageWordId": "rlabel-2", "matchType": "matched" },
    { "audioWord": "Measure", "start": 1.7, "end": 1.92, "pageWordId": "rlabel-3", "matchType": "matched" },
    { "audioWord": "distance.", "start": 1.92, "end": 2.42, "pageWordId": "rlabel-4", "matchType": "matched" },
    
    { "audioWord": "Let's", "start": 3.1, "end": 3.36, "pageWordId": "rsub-1", "matchType": "matched" },
    { "audioWord": "find", "start": 3.36, "end": 3.7, "pageWordId": "rsub-2", "matchType": "matched" },
    { "audioWord": "the", "start": 3.7, "end": 3.92, "pageWordId": "rsub-3", "matchType": "matched" },
    { "audioWord": "real", "start": 3.92, "end": 4.1, "pageWordId": "rsub-4", "matchType": "matched" },
    { "audioWord": "distance", "start": 4.1, "end": 4.6, "pageWordId": "rsub-5", "matchType": "matched" },
    { "audioWord": "using", "start": 4.6, "end": 5.02, "pageWordId": "rsub-6", "matchType": "matched" },
    { "audioWord": "the", "start": 5.02, "end": 5.28, "pageWordId": "rsub-7", "matchType": "matched" },
    { "audioWord": "map", "start": 5.28, "end": 5.5, "pageWordId": "rsub-8", "matchType": "matched" },
    { "audioWord": "scale.", "start": 5.5, "end": 5.8, "pageWordId": "rsub-9", "matchType": "matched" },

    { "audioWord": "Step", "start": 6.48, "end": 6.66, "pageWordId": "step1-num-1", "matchType": "matched" },
    { "audioWord": "one,", "start": 6.66, "end": 7.2, "pageWordId": "step1-num-2", "matchType": "matched" },

    { "audioWord": "know", "start": 7.56, "end": 7.7, "pageWordId": "step1-title-1", "matchType": "matched" },
    { "audioWord": "the", "start": 7.7, "end": 7.96, "pageWordId": "step1-title-2", "matchType": "matched" },
    { "audioWord": "scale.", "start": 7.96, "end": 8.1, "pageWordId": "step1-title-3", "matchType": "matched" },

    { "audioWord": "A", "start": 8.68, "end": 8.84, "pageWordId": "card1-desc-1", "matchType": "matched" },
    { "audioWord": "real", "start": 8.84, "end": 9.06, "pageWordId": "card1-desc-2", "matchType": "matched" },
    { "audioWord": "place", "start": 9.06, "end": 9.42, "pageWordId": "card1-desc-3", "matchType": "matched" },
    { "audioWord": "is", "start": 9.42, "end": 9.84, "pageWordId": "card1-desc-4", "matchType": "matched" },
    { "audioWord": "much", "start": 9.84, "end": 10.06, "pageWordId": "card1-desc-5", "matchType": "matched" },
    { "audioWord": "bigger", "start": 10.06, "end": 10.34, "pageWordId": "card1-desc-6", "matchType": "matched" },
    { "audioWord": "than", "start": 10.34, "end": 10.56, "pageWordId": "card1-desc-7", "matchType": "matched" },
    { "audioWord": "its", "start": 10.56, "end": 10.78, "pageWordId": "card1-desc-8", "matchType": "matched" },
    { "audioWord": "map", "start": 10.78, "end": 11.0, "pageWordId": "card1-desc-9", "matchType": "matched" },
    { "audioWord": "drawing.", "start": 11.0, "end": 11.36, "pageWordId": "card1-desc-10", "matchType": "matched" },

    { "audioWord": "A", "start": 12.08, "end": 12.24, "pageWordId": "card2-desc-1", "matchType": "matched" },
    { "audioWord": "long", "start": 12.24, "end": 12.44, "pageWordId": "card2-desc-2", "matchType": "matched" },
    { "audioWord": "real", "start": 12.44, "end": 12.7, "pageWordId": "card2-desc-3", "matchType": "matched" },
    { "audioWord": "distance", "start": 12.7, "end": 13.16, "pageWordId": "card2-desc-4", "matchType": "matched" },
    { "audioWord": "is", "start": 13.16, "end": 13.5, "pageWordId": "card2-desc-5", "matchType": "matched" },
    { "audioWord": "shown", "start": 13.5, "end": 13.76, "pageWordId": "card2-desc-6", "matchType": "matched" },
    { "audioWord": "as", "start": 13.76, "end": 14.16, "pageWordId": "card2-desc-7", "matchType": "matched" },
    { "audioWord": "a", "start": 14.16, "end": 14.42, "pageWordId": "card2-desc-8", "matchType": "matched" },
    { "audioWord": "shorter", "start": 14.42, "end": 14.66, "pageWordId": "card2-desc-9", "matchType": "matched" },
    { "audioWord": "map", "start": 14.66, "end": 15.08, "pageWordId": "card2-desc-10", "matchType": "matched" },
    { "audioWord": "distance.", "start": 15.08, "end": 15.36, "pageWordId": "card2-desc-11", "matchType": "matched" },

    { "audioWord": "Places", "start": 16.46, "end": 16.9, "pageWordId": "card3-desc-1", "matchType": "matched" },
    { "audioWord": "keep", "start": 16.9, "end": 17.28, "pageWordId": "card3-desc-2", "matchType": "matched" },
    { "audioWord": "their", "start": 17.28, "end": 17.6, "pageWordId": "card3-desc-3", "matchType": "matched" },
    { "audioWord": "relative", "start": 17.6, "end": 17.92, "pageWordId": "card3-desc-4", "matchType": "matched" },
    { "audioWord": "positions", "start": 17.92, "end": 18.42, "pageWordId": "card3-desc-5", "matchType": "matched" },
    { "audioWord": "on", "start": 18.42, "end": 18.78, "pageWordId": "card3-desc-6", "matchType": "matched" },
    { "audioWord": "the", "start": 18.78, "end": 18.96, "pageWordId": "card3-desc-7", "matchType": "matched" },
    { "audioWord": "map.", "start": 18.96, "end": 19.14, "pageWordId": "card3-desc-8", "matchType": "matched" },

    { "audioWord": "Remember,", "start": 19.72, "end": 20.26, "pageWordId": "rem-title-1", "matchType": "matched" },
    { "audioWord": "maps", "start": 20.64, "end": 20.9, "pageWordId": "rem-desc-1", "matchType": "matched" },
    { "audioWord": "are", "start": 20.9, "end": 21.22, "pageWordId": "rem-desc-2", "matchType": "matched" },
    { "audioWord": "smaller,", "start": 21.22, "end": 21.54, "pageWordId": "rem-desc-3", "matchType": "matched" },
    { "audioWord": "but", "start": 21.9, "end": 22.08, "pageWordId": "rem-desc-4", "matchType": "matched" },
    { "audioWord": "the", "start": 22.08, "end": 22.38, "pageWordId": "rem-desc-5", "matchType": "matched" },
    { "audioWord": "scale", "start": 22.38, "end": 22.58, "pageWordId": "rem-desc-6", "matchType": "matched" },
    { "audioWord": "tells", "start": 22.58, "end": 22.9, "pageWordId": "rem-desc-7", "matchType": "matched" },
    { "audioWord": "us", "start": 22.9, "end": 23.16, "pageWordId": "rem-desc-8", "matchType": "matched" },
    { "audioWord": "the", "start": 23.16, "end": 23.36, "pageWordId": "rem-desc-9", "matchType": "matched" },
    { "audioWord": "real", "start": 23.36, "end": 23.56, "pageWordId": "rem-desc-10", "matchType": "matched" },
    { "audioWord": "distance.", "start": 23.56, "end": 24.02, "pageWordId": "rem-desc-11", "matchType": "matched" }
];
