export const PAGE40_TRANSCRIPT = [
  // Title (prefix: t)
  { "audioWord": "understanding", "start": 0.0, "end": 0.72, "pageWordId": "t-1", "matchType": "matched" },
  { "audioWord": "map", "start": 0.72, "end": 1.0, "pageWordId": "t-2", "matchType": "matched" },
  { "audioWord": "symbols,", "start": 1.0, "end": 1.54, "pageWordId": "t-3", "matchType": "matched" },
  
  // Subtitle (prefix: s)
  { "audioWord": "small", "start": 2.32, "end": 2.5, "pageWordId": "s-1", "matchType": "matched" },
  { "audioWord": "drawings", "start": 2.5, "end": 2.9, "pageWordId": "s-2", "matchType": "matched" },
  { "audioWord": "and", "start": 2.9, "end": 3.2, "pageWordId": "s-3", "matchType": "matched" },
  { "audioWord": "shapes", "start": 3.2, "end": 3.48, "pageWordId": "s-4", "matchType": "matched" },
  { "audioWord": "that", "start": 3.48, "end": 3.84, "pageWordId": "s-5", "matchType": "matched" },
  { "audioWord": "represent", "start": 3.84, "end": 4.26, "pageWordId": "s-6", "matchType": "matched" },
  { "audioWord": "real", "start": 4.26, "end": 4.58, "pageWordId": "s-7", "matchType": "matched" },
  { "audioWord": "places", "start": 4.58, "end": 4.96, "pageWordId": "s-8", "matchType": "matched" },
  { "audioWord": "on", "start": 4.96, "end": 5.26, "pageWordId": "s-9", "matchType": "matched" },
  { "audioWord": "earth.", "start": 5.26, "end": 5.42, "pageWordId": "s-10", "matchType": "matched" },
  
  // H2 (prefix: h)
  { "audioWord": "What", "start": 6.08, "end": 6.28, "pageWordId": "h-1", "matchType": "matched" },
  { "audioWord": "are", "start": 6.28, "end": 6.42, "pageWordId": "h-2", "matchType": "matched" },
  { "audioWord": "symbols?", "start": 6.42, "end": 6.82, "pageWordId": "h-3", "matchType": "matched" },
  
  // Paragraph (prefix: p)
  { "audioWord": "Real", "start": 8.36, "end": 8.6, "pageWordId": "p-1", "matchType": "matched" },
  { "audioWord": "places", "start": 8.6, "end": 8.96, "pageWordId": "p-2", "matchType": "matched" },
  { "audioWord": "are", "start": 8.96, "end": 9.2, "pageWordId": "p-3", "matchType": "matched" },
  { "audioWord": "too", "start": 9.2, "end": 9.44, "pageWordId": "p-4", "matchType": "matched" },
  { "audioWord": "big", "start": 9.44, "end": 9.6, "pageWordId": "p-5", "matchType": "matched" },
  { "audioWord": "to", "start": 9.6, "end": 9.78, "pageWordId": "p-6", "matchType": "matched" },
  { "audioWord": "draw", "start": 9.78, "end": 9.94, "pageWordId": "p-7", "matchType": "matched" },
  { "audioWord": "on", "start": 9.94, "end": 10.16, "pageWordId": "p-8", "matchType": "matched" },
  { "audioWord": "a", "start": 10.16, "end": 10.32, "pageWordId": "p-9", "matchType": "matched" },
  { "audioWord": "map.", "start": 10.32, "end": 10.56, "pageWordId": "p-10", "matchType": "matched" },
  { "audioWord": "Instead", "start": 11.02, "end": 11.3, "pageWordId": "p-11", "matchType": "matched" },
  { "audioWord": "of", "start": 11.3, "end": 11.54, "pageWordId": "p-12", "matchType": "matched" },
  { "audioWord": "drawing", "start": 11.54, "end": 11.84, "pageWordId": "p-13", "matchType": "matched" },
  { "audioWord": "real", "start": 11.84, "end": 12.18, "pageWordId": "p-14", "matchType": "matched" },
  { "audioWord": "buildings,", "start": 12.18, "end": 12.64, "pageWordId": "p-15", "matchType": "matched" },
  { "audioWord": "roads", "start": 13.02, "end": 13.32, "pageWordId": "p-16", "matchType": "matched" },
  { "audioWord": "and", "start": 13.32, "end": 13.9, "pageWordId": "p-17", "matchType": "matched" },
  { "audioWord": "rivers,", "start": 13.9, "end": 14.28, "pageWordId": "p-18", "matchType": "matched" },
  { "audioWord": "we", "start": 14.82, "end": 15.04, "pageWordId": "p-19", "matchType": "matched" },
  { "audioWord": "use", "start": 15.04, "end": 15.38, "pageWordId": "p-20", "matchType": "matched" },
  { "audioWord": "simple", "start": 15.38, "end": 15.76, "pageWordId": "p-21", "matchType": "matched" },
  { "audioWord": "symbols", "start": 15.76, "end": 16.18, "pageWordId": "p-22", "matchType": "matched" },
  { "audioWord": "to", "start": 16.18, "end": 16.72, "pageWordId": "p-23", "matchType": "matched" },
  { "audioWord": "make", "start": 16.72, "end": 16.96, "pageWordId": "p-24", "matchType": "matched" },
  { "audioWord": "maps", "start": 16.96, "end": 17.34, "pageWordId": "p-25", "matchType": "matched" },
  { "audioWord": "easy", "start": 17.34, "end": 17.76, "pageWordId": "p-26", "matchType": "matched" },
  { "audioWord": "to", "start": 17.76, "end": 18.0, "pageWordId": "p-27", "matchType": "matched" },
  { "audioWord": "read.", "start": 18.0, "end": 18.2, "pageWordId": "p-28", "matchType": "matched" },
  
  // Unmatched
  { "audioWord": "There", "start": 18.74, "end": 18.94, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "are", "start": 18.94, "end": 19.12, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "many", "start": 19.12, "end": 19.42, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "different", "start": 19.42, "end": 19.74, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "symbols", "start": 19.74, "end": 20.08, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "used", "start": 20.08, "end": 20.44, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "on", "start": 20.44, "end": 20.68, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "maps.", "start": 20.68, "end": 21.02, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "Let's", "start": 21.52, "end": 21.8, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "look", "start": 21.8, "end": 21.98, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "at", "start": 21.98, "end": 22.12, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "some", "start": 22.12, "end": 22.38, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "common", "start": 22.38, "end": 22.66, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "ones", "start": 22.66, "end": 22.92, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "below.", "start": 22.92, "end": 23.24, "pageWordId": "none", "matchType": "unmatched" }
];
