export const PAGE37_TRANSCRIPT = [
  { "audioWord": "Which", "start": 0.0, "end": 0.46, "pageWordId": "q-1", "matchType": "matched" },
  { "audioWord": "direction", "start": 0.46, "end": 0.94, "pageWordId": "q-2", "matchType": "matched" },
  { "audioWord": "should", "start": 0.94, "end": 1.18, "pageWordId": "q-3", "matchType": "matched" },
  { "audioWord": "we", "start": 1.18, "end": 1.42, "pageWordId": "q-4", "matchType": "matched" },
  { "audioWord": "travel", "start": 1.42, "end": 1.68, "pageWordId": "q-5", "matchType": "matched" },
  { "audioWord": "from", "start": 1.68, "end": 2.08, "pageWordId": "q-6", "matchType": "matched" },
  { "audioWord": "Chennai", "start": 2.08, "end": 2.48, "pageWordId": "q-7", "matchType": "matched" },
  { "audioWord": "to", "start": 2.48, "end": 2.7, "pageWordId": "q-8", "matchType": "matched" },
  { "audioWord": "reach", "start": 2.7, "end": 3.04, "pageWordId": "q-9", "matchType": "matched" },
  { "audioWord": "Kolkata?", "start": 3.04, "end": 3.78, "pageWordId": "q-10", "matchType": "matched" },
  { "audioWord": "Think", "start": 4.88, "end": 5.1, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "about", "start": 5.1, "end": 5.38, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "where", "start": 5.38, "end": 5.56, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "Kolkata", "start": 5.56, "end": 6.14, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "lies", "start": 6.14, "end": 6.4, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "on", "start": 6.4, "end": 6.66, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "the", "start": 6.66, "end": 6.8, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "map,", "start": 6.8, "end": 7.02, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "then", "start": 7.54, "end": 7.66, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "make", "start": 7.66, "end": 7.86, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "your", "start": 7.86, "end": 8.08, "pageWordId": "none", "matchType": "unmatched" },
  { "audioWord": "choice.", "start": 8.08, "end": 8.42, "pageWordId": "none", "matchType": "unmatched" }
];
