export const PAGE5P2_TRANSCRIPT = [
  { "audioWord": "Welcome", "start": 0.0, "end": 0.44, "pageWordId": "welcome-1", "matchType": "matched" },
  { "audioWord": "to", "start": 0.44, "end": 0.66, "pageWordId": "welcome-2", "matchType": "matched" },
  { "audioWord": "the", "start": 0.66, "end": 0.8, "pageWordId": "welcome-3", "matchType": "matched" },
  { "audioWord": "city.", "start": 0.8, "end": 1.14, "pageWordId": "welcome-4", "matchType": "matched" },
  { "audioWord": "Help", "start": 1.6, "end": 1.84, "pageWordId": "help-1", "matchType": "matched" },
  { "audioWord": "Spider-Man", "start": 1.84, "end": 2.44, "pageWordId": "help-2", "matchType": "matched" },
  { "audioWord": "travel", "start": 2.44, "end": 2.82, "pageWordId": "help-3", "matchType": "matched" },
  { "audioWord": "from", "start": 2.82, "end": 3.08, "pageWordId": "help-4", "matchType": "matched" },
  { "audioWord": "the", "start": 3.08, "end": 3.32, "pageWordId": "help-5", "matchType": "matched" },
  { "audioWord": "airport", "start": 3.32, "end": 3.56, "pageWordId": "help-6", "matchType": "matched" },
  { "audioWord": "to", "start": 3.56, "end": 3.92, "pageWordId": "help-7", "matchType": "matched" },
  { "audioWord": "Sunset", "start": 3.92, "end": 4.38, "pageWordId": "help-8", "matchType": "matched" },
  { "audioWord": "Beach.", "start": 4.38, "end": 4.7, "pageWordId": "help-9", "matchType": "matched" },
  { "audioWord": "Use", "start": 5.22, "end": 5.5, "pageWordId": "use-1", "matchType": "matched" },
  { "audioWord": "the", "start": 5.5, "end": 5.78, "pageWordId": "use-2", "matchType": "matched" },
  { "audioWord": "direction", "start": 5.78, "end": 6.18, "pageWordId": "use-3", "matchType": "matched" },
  { "audioWord": "controls", "start": 6.18, "end": 6.62, "pageWordId": "use-4", "matchType": "matched" },
  { "audioWord": "to", "start": 6.62, "end": 6.92, "pageWordId": "use-5", "matchType": "matched" },
  { "audioWord": "guide", "start": 6.92, "end": 7.08, "pageWordId": "use-6", "matchType": "matched" },
  { "audioWord": "him", "start": 7.08, "end": 7.34, "pageWordId": "use-7", "matchType": "matched" },
  { "audioWord": "safely.", "start": 7.34, "end": 7.74, "pageWordId": "use-8", "matchType": "matched" },
  { "audioWord": "Let's", "start": 8.32, "end": 8.64, "pageWordId": "lets-1", "matchType": "matched" },
  { "audioWord": "go.", "start": 8.64, "end": 8.78, "pageWordId": "lets-2", "matchType": "matched" }
];
