export const PAGE51_TRANSCRIPT = [
  // Title: "Latitude and Climate"
  { "audioWord": "Latitude", "start": 0.0, "end": 0.68, "pageWordId": "h-1", "matchType": "matched" },
  { "audioWord": "and", "start": 0.68, "end": 1.02, "pageWordId": "h-2", "matchType": "matched" },
  { "audioWord": "climate", "start": 1.02, "end": 1.38, "pageWordId": "h-3", "matchType": "matched" },

  // p1: "Latitude is linked to **climate**. The coloured belts on the globe show the three zones. Near the Equator, it is generally **hot** — the **torrid** zone (orange), bounded by the **Tropic** **of** **Cancer** (23½°N) and **Tropic** **of** **Capricorn** (23½°S)."
  { "audioWord": "latitude", "start": 1.38, "end": 1.84, "pageWordId": "p1-1", "matchType": "matched" },
  { "audioWord": "is", "start": 1.84, "end": 2.12, "pageWordId": "p1-2", "matchType": "matched" },
  { "audioWord": "linked", "start": 2.12, "end": 2.34, "pageWordId": "p1-3", "matchType": "matched" },
  { "audioWord": "to", "start": 2.34, "end": 2.62, "pageWordId": "p1-4", "matchType": "matched" },
  { "audioWord": "climate.", "start": 2.62, "end": 2.94, "pageWordId": "p1-5", "matchType": "matched" },
  { "audioWord": "The", "start": 3.6, "end": 3.84, "pageWordId": "p1-6", "matchType": "matched" },
  { "audioWord": "colored", "start": 3.84, "end": 4.04, "pageWordId": "p1-7", "matchType": "matched" },
  { "audioWord": "belts", "start": 4.04, "end": 4.38, "pageWordId": "p1-8", "matchType": "matched" },
  { "audioWord": "on", "start": 4.38, "end": 4.58, "pageWordId": "p1-9", "matchType": "matched" },
  { "audioWord": "the", "start": 4.58, "end": 4.8, "pageWordId": "p1-10", "matchType": "matched" },
  { "audioWord": "globe", "start": 4.8, "end": 5.04, "pageWordId": "p1-11", "matchType": "matched" },
  { "audioWord": "show", "start": 5.04, "end": 5.34, "pageWordId": "p1-12", "matchType": "matched" },
  { "audioWord": "the", "start": 5.34, "end": 5.58, "pageWordId": "p1-13", "matchType": "matched" },
  { "audioWord": "three", "start": 5.58, "end": 5.8, "pageWordId": "p1-14", "matchType": "matched" },
  { "audioWord": "zones.", "start": 5.8, "end": 6.16, "pageWordId": "p1-15", "matchType": "matched" },
  { "audioWord": "Near", "start": 6.84, "end": 7.06, "pageWordId": "p1-16", "matchType": "matched" },
  { "audioWord": "the", "start": 7.06, "end": 7.36, "pageWordId": "p1-17", "matchType": "matched" },
  { "audioWord": "equator,", "start": 7.36, "end": 7.66, "pageWordId": "p1-18", "matchType": "matched" },
  { "audioWord": "it", "start": 7.82, "end": 7.96, "pageWordId": "p1-19", "matchType": "matched" },
  { "audioWord": "is", "start": 7.96, "end": 8.18, "pageWordId": "p1-20", "matchType": "matched" },
  { "audioWord": "generally", "start": 8.18, "end": 8.56, "pageWordId": "p1-21", "matchType": "matched" },
  { "audioWord": "hot.", "start": 8.56, "end": 9.0, "pageWordId": "p1-22", "matchType": "matched" },
  { "audioWord": "The", "start": 9.56, "end": 9.76, "pageWordId": "p1-24", "matchType": "matched" },
  { "audioWord": "torrid", "start": 9.76, "end": 10.1, "pageWordId": "p1-25", "matchType": "matched" },
  { "audioWord": "zone,", "start": 10.1, "end": 10.4, "pageWordId": "p1-26", "matchType": "matched" },
  { "audioWord": "orange,", "start": 10.88, "end": 11.28, "pageWordId": "p1-27", "matchType": "matched" },
  { "audioWord": "bounded", "start": 11.76, "end": 12.0, "pageWordId": "p1-28", "matchType": "matched" },
  { "audioWord": "by", "start": 12.0, "end": 12.32, "pageWordId": "p1-29", "matchType": "matched" },
  { "audioWord": "the", "start": 12.32, "end": 12.52, "pageWordId": "p1-30", "matchType": "matched" },
  { "audioWord": "Tropic", "start": 12.52, "end": 12.76, "pageWordId": "p1-31", "matchType": "matched" },
  { "audioWord": "of", "start": 12.76, "end": 12.94, "pageWordId": "p1-32", "matchType": "matched" },
  { "audioWord": "Cancer", "start": 12.94, "end": 13.38, "pageWordId": "p1-33", "matchType": "matched" },
  { "audioWord": "and", "start": 13.38, "end": 13.84, "pageWordId": "p1-35", "matchType": "matched" },
  { "audioWord": "Tropic", "start": 13.84, "end": 14.2, "pageWordId": "p1-36", "matchType": "matched" },
  { "audioWord": "of", "start": 14.2, "end": 14.44, "pageWordId": "p1-37", "matchType": "matched" },
  { "audioWord": "Capricorn.", "start": 14.44, "end": 15.28, "pageWordId": "p1-38", "matchType": "matched" },

  // p3: "Moving away from the Equator the climate becomes **temperate** (green, mild); beyond the **Arctic** **Circle** (66½°N) and **Antarctic** **Circle** (66½°S) it is **frigid** (blue, very cold). Latitude also helps explain the **seasons**."
  { "audioWord": "Moving", "start": 15.7, "end": 15.96, "pageWordId": "p3-1", "matchType": "matched" },
  { "audioWord": "away", "start": 15.96, "end": 16.26, "pageWordId": "p3-2", "matchType": "matched" },
  { "audioWord": "from", "start": 16.26, "end": 16.48, "pageWordId": "p3-3", "matchType": "matched" },
  { "audioWord": "the", "start": 16.48, "end": 16.72, "pageWordId": "p3-4", "matchType": "matched" },
  { "audioWord": "equator,", "start": 16.72, "end": 17.02, "pageWordId": "p3-5", "matchType": "matched" },
  { "audioWord": "the", "start": 17.26, "end": 17.4, "pageWordId": "p3-6", "matchType": "matched" },
  { "audioWord": "climate", "start": 17.4, "end": 17.64, "pageWordId": "p3-7", "matchType": "matched" },
  { "audioWord": "becomes", "start": 17.64, "end": 18.1, "pageWordId": "p3-8", "matchType": "matched" },
  { "audioWord": "temperate,", "start": 18.1, "end": 18.86, "pageWordId": "p3-9", "matchType": "matched" },
  { "audioWord": "green,", "start": 19.26, "end": 19.56, "pageWordId": "p3-10", "matchType": "matched" },
  { "audioWord": "mild.", "start": 19.92, "end": 20.2, "pageWordId": "p3-11", "matchType": "matched" },
  { "audioWord": "Beyond", "start": 20.72, "end": 21.0, "pageWordId": "p3-12", "matchType": "matched" },
  { "audioWord": "the", "start": 21.0, "end": 21.3, "pageWordId": "p3-13", "matchType": "matched" },
  { "audioWord": "Arctic", "start": 21.3, "end": 21.54, "pageWordId": "p3-14", "matchType": "matched" },
  { "audioWord": "Circle", "start": 21.54, "end": 21.94, "pageWordId": "p3-15", "matchType": "matched" },
  { "audioWord": "and", "start": 21.94, "end": 22.24, "pageWordId": "p3-17", "matchType": "matched" },
  { "audioWord": "Antarctic", "start": 22.24, "end": 22.82, "pageWordId": "p3-18", "matchType": "matched" },
  { "audioWord": "Circle,", "start": 22.82, "end": 23.28, "pageWordId": "p3-19", "matchType": "matched" },
  { "audioWord": "it", "start": 23.66, "end": 23.7, "pageWordId": "p3-21", "matchType": "matched" },
  { "audioWord": "is", "start": 23.7, "end": 23.96, "pageWordId": "p3-22", "matchType": "matched" },
  { "audioWord": "frigid.", "start": 23.96, "end": 24.54, "pageWordId": "p3-23", "matchType": "matched" },
  { "audioWord": "Latitude", "start": 25.06, "end": 25.52, "pageWordId": "p3-27", "matchType": "matched" },
  { "audioWord": "also", "start": 25.52, "end": 25.88, "pageWordId": "p3-28", "matchType": "matched" },
  { "audioWord": "helps", "start": 25.88, "end": 26.18, "pageWordId": "p3-29", "matchType": "matched" },
  { "audioWord": "explain", "start": 26.18, "end": 26.64, "pageWordId": "p3-30", "matchType": "matched" },
  { "audioWord": "the", "start": 26.64, "end": 26.9, "pageWordId": "p3-31", "matchType": "matched" },
  { "audioWord": "seasons.", "start": 26.9, "end": 27.22, "pageWordId": "p3-32", "matchType": "matched" }
];
