export const PAGE60_TRANSCRIPT = [
  // h: "Northern & Southern Hemispheres"
  { "audioWord": "northern", "start": 0.0, "end": 0.44, "pageWordId": "h-1", "matchType": "matched" },
  { "audioWord": "and", "start": 0.44, "end": 0.66, "pageWordId": "h-2", "matchType": "matched" },
  { "audioWord": "southern", "start": 0.66, "end": 1.0, "pageWordId": "h-3", "matchType": "matched" },
  { "audioWord": "hemispheres.", "start": 1.0, "end": 1.74, "pageWordId": "h-4", "matchType": "matched" },

  // p1: "Now cut the globe along the **Equator** **(0°)** instead. Again it opens into two halves shown **fully**."
  { "audioWord": "Now", "start": 2.36, "end": 2.54, "pageWordId": "p1-1", "matchType": "matched" },
  { "audioWord": "cut", "start": 2.54, "end": 2.76, "pageWordId": "p1-2", "matchType": "matched" },
  { "audioWord": "the", "start": 2.76, "end": 2.96, "pageWordId": "p1-3", "matchType": "matched" },
  { "audioWord": "globe", "start": 2.96, "end": 3.18, "pageWordId": "p1-4", "matchType": "matched" },
  { "audioWord": "along", "start": 3.18, "end": 3.48, "pageWordId": "p1-5", "matchType": "matched" },
  { "audioWord": "the", "start": 3.48, "end": 3.78, "pageWordId": "p1-6", "matchType": "matched" },
  { "audioWord": "equator,", "start": 3.78, "end": 4.16, "pageWordId": "p1-7", "matchType": "matched" },
  { "audioWord": "zero", "start": 4.78, "end": 4.98, "pageWordId": "p1-8", "matchType": "matched" },
  { "audioWord": "degrees", "start": 4.98, "end": 5.38, "pageWordId": "p1-8", "matchType": "matched" },
  { "audioWord": "instead.", "start": 5.38, "end": 5.94, "pageWordId": "p1-9", "matchType": "matched" },
  { "audioWord": "Again", "start": 6.56, "end": 6.74, "pageWordId": "p1-10", "matchType": "matched" },
  { "audioWord": "it", "start": 6.74, "end": 6.96, "pageWordId": "p1-11", "matchType": "matched" },
  { "audioWord": "opens", "start": 6.96, "end": 7.24, "pageWordId": "p1-12", "matchType": "matched" },
  { "audioWord": "into", "start": 7.24, "end": 7.6, "pageWordId": "p1-13", "matchType": "matched" },
  { "audioWord": "two", "start": 7.6, "end": 7.92, "pageWordId": "p1-14", "matchType": "matched" },
  { "audioWord": "halves", "start": 7.92, "end": 8.26, "pageWordId": "p1-15", "matchType": "matched" },
  { "audioWord": "shown", "start": 8.26, "end": 8.68, "pageWordId": "p1-16", "matchType": "matched" },
  { "audioWord": "fully.", "start": 8.68, "end": 9.02, "pageWordId": "p1-17", "matchType": "matched" },

  // p2: "The top half (green) is the **Northern** **Hemisphere**; the bottom half (purple) is the **Southern** **Hemisphere**. India lies in the Northern Hemisphere."
  { "audioWord": "The", "start": 9.82, "end": 9.96, "pageWordId": "p2-1", "matchType": "matched" },
  { "audioWord": "top", "start": 9.96, "end": 10.16, "pageWordId": "p2-2", "matchType": "matched" },
  { "audioWord": "half", "start": 10.16, "end": 10.44, "pageWordId": "p2-3", "matchType": "matched" },
  { "audioWord": "is", "start": 10.44, "end": 10.74, "pageWordId": "p2-5", "matchType": "matched" },
  { "audioWord": "the", "start": 10.74, "end": 10.88, "pageWordId": "p2-6", "matchType": "matched" },
  { "audioWord": "northern", "start": 10.88, "end": 11.12, "pageWordId": "p2-7", "matchType": "matched" },
  { "audioWord": "hemisphere.", "start": 11.12, "end": 11.6, "pageWordId": "p2-8", "matchType": "matched" },
  { "audioWord": "The", "start": 12.22, "end": 12.4, "pageWordId": "p2-9", "matchType": "matched" },
  { "audioWord": "bottom", "start": 12.4, "end": 12.62, "pageWordId": "p2-10", "matchType": "matched" },
  { "audioWord": "half", "start": 12.62, "end": 12.96, "pageWordId": "p2-11", "matchType": "matched" },
  { "audioWord": "is", "start": 12.96, "end": 13.26, "pageWordId": "p2-13", "matchType": "matched" },
  { "audioWord": "the", "start": 13.26, "end": 13.48, "pageWordId": "p2-14", "matchType": "matched" },
  { "audioWord": "southern", "start": 13.48, "end": 13.66, "pageWordId": "p2-15", "matchType": "matched" },
  { "audioWord": "hemisphere.", "start": 13.66, "end": 14.2, "pageWordId": "p2-16", "matchType": "matched" },
  { "audioWord": "India", "start": 15.0, "end": 15.34, "pageWordId": "p2-17", "matchType": "matched" },
  { "audioWord": "lies", "start": 15.34, "end": 15.82, "pageWordId": "p2-18", "matchType": "matched" },
  { "audioWord": "in", "start": 15.82, "end": 16.06, "pageWordId": "p2-19", "matchType": "matched" },
  { "audioWord": "the", "start": 16.06, "end": 16.22, "pageWordId": "p2-20", "matchType": "matched" },
  { "audioWord": "northern", "start": 16.22, "end": 16.44, "pageWordId": "p2-21", "matchType": "matched" },
  { "audioWord": "hemisphere.", "start": 16.44, "end": 16.88, "pageWordId": "p2-22", "matchType": "matched" }
];
