export const PAGE53_TRANSCRIPT = [
  // Title: "What is Longitude?"
  { "audioWord": "What", "start": 0.0, "end": 0.28, "pageWordId": "h-1", "matchType": "matched" },
  { "audioWord": "is", "start": 0.28, "end": 0.5, "pageWordId": "h-2", "matchType": "matched" },
  { "audioWord": "longitude?", "start": 0.5, "end": 1.08, "pageWordId": "h-3", "matchType": "matched" },

  // p1: "Now imagine standing on the Prime Meridian and travelling **east** **or** **west** along the Equator. Your **distance** from the Prime Meridian keeps increasing."
  { "audioWord": "Now", "start": 1.94, "end": 2.12, "pageWordId": "p1-1", "matchType": "matched" },
  { "audioWord": "imagine", "start": 2.12, "end": 2.64, "pageWordId": "p1-2", "matchType": "matched" },
  { "audioWord": "standing", "start": 2.64, "end": 3.0, "pageWordId": "p1-3", "matchType": "matched" },
  { "audioWord": "on", "start": 3.0, "end": 3.24, "pageWordId": "p1-4", "matchType": "matched" },
  { "audioWord": "the", "start": 3.24, "end": 3.48, "pageWordId": "p1-5", "matchType": "matched" },
  { "audioWord": "prime", "start": 3.48, "end": 3.66, "pageWordId": "p1-6", "matchType": "matched" },
  { "audioWord": "meridian", "start": 3.66, "end": 4.06, "pageWordId": "p1-7", "matchType": "matched" },
  { "audioWord": "and", "start": 4.06, "end": 4.7, "pageWordId": "p1-8", "matchType": "matched" },
  { "audioWord": "travelling", "start": 4.7, "end": 5.06, "pageWordId": "p1-9", "matchType": "matched" },
  { "audioWord": "east", "start": 5.06, "end": 5.54, "pageWordId": "p1-10", "matchType": "matched" },
  { "audioWord": "or", "start": 5.54, "end": 5.84, "pageWordId": "p1-11", "matchType": "matched" },
  { "audioWord": "west", "start": 5.84, "end": 6.2, "pageWordId": "p1-12", "matchType": "matched" },
  { "audioWord": "along", "start": 6.2, "end": 6.54, "pageWordId": "p1-13", "matchType": "matched" },
  { "audioWord": "the", "start": 6.54, "end": 6.88, "pageWordId": "p1-14", "matchType": "matched" },
  { "audioWord": "equator.", "start": 6.88, "end": 7.2, "pageWordId": "p1-15", "matchType": "matched" },
  { "audioWord": "Your", "start": 8.08, "end": 8.28, "pageWordId": "p1-16", "matchType": "matched" },
  { "audioWord": "distance", "start": 8.28, "end": 8.72, "pageWordId": "p1-17", "matchType": "matched" },
  { "audioWord": "from", "start": 8.72, "end": 8.98, "pageWordId": "p1-18", "matchType": "matched" },
  { "audioWord": "the", "start": 8.98, "end": 9.22, "pageWordId": "p1-19", "matchType": "matched" },
  { "audioWord": "prime", "start": 9.22, "end": 9.44, "pageWordId": "p1-20", "matchType": "matched" },
  { "audioWord": "meridian", "start": 9.44, "end": 9.88, "pageWordId": "p1-21", "matchType": "matched" },
  { "audioWord": "keeps", "start": 9.88, "end": 10.3, "pageWordId": "p1-22", "matchType": "matched" },
  { "audioWord": "increasing.", "start": 10.3, "end": 10.96, "pageWordId": "p1-23", "matchType": "matched" },

  // p2: "**Longitude** is exactly this — a measure of how far **east** **or** **west** of the Prime Meridian a place is."
  { "audioWord": "Longitude", "start": 11.78, "end": 12.24, "pageWordId": "p2-1", "matchType": "matched" },
  { "audioWord": "is", "start": 12.24, "end": 12.46, "pageWordId": "p2-2", "matchType": "matched" },
  { "audioWord": "exactly", "start": 12.46, "end": 12.88, "pageWordId": "p2-3", "matchType": "matched" },
  { "audioWord": "this,", "start": 12.88, "end": 13.36, "pageWordId": "p2-4", "matchType": "matched" },
  { "audioWord": "a", "start": 13.98, "end": 14.06, "pageWordId": "p2-6", "matchType": "matched" },
  { "audioWord": "measure", "start": 14.06, "end": 14.36, "pageWordId": "p2-7", "matchType": "matched" },
  { "audioWord": "of", "start": 14.36, "end": 14.94, "pageWordId": "p2-8", "matchType": "matched" },
  { "audioWord": "how", "start": 14.94, "end": 15.28, "pageWordId": "p2-9", "matchType": "matched" },
  { "audioWord": "far", "start": 15.28, "end": 15.62, "pageWordId": "p2-10", "matchType": "matched" },
  { "audioWord": "east", "start": 15.62, "end": 15.98, "pageWordId": "p2-11", "matchType": "matched" },
  { "audioWord": "or", "start": 15.98, "end": 16.24, "pageWordId": "p2-12", "matchType": "matched" },
  { "audioWord": "west", "start": 16.24, "end": 16.6, "pageWordId": "p2-13", "matchType": "matched" },
  { "audioWord": "of", "start": 16.6, "end": 16.82, "pageWordId": "p2-14", "matchType": "matched" },
  { "audioWord": "the", "start": 16.82, "end": 17.04, "pageWordId": "p2-15", "matchType": "matched" },
  { "audioWord": "prime", "start": 17.04, "end": 17.24, "pageWordId": "p2-16", "matchType": "matched" },
  { "audioWord": "meridian", "start": 17.24, "end": 17.62, "pageWordId": "p2-17", "matchType": "matched" },
  { "audioWord": "a", "start": 17.62, "end": 17.96, "pageWordId": "p2-18", "matchType": "matched" },
  { "audioWord": "place", "start": 17.96, "end": 18.18, "pageWordId": "p2-19", "matchType": "matched" },
  { "audioWord": "is.", "start": 18.18, "end": 18.78, "pageWordId": "p2-20", "matchType": "matched" },

  // p3: "(Latitude measured distance **north–south**; longitude measures it **east–west**.)"
  { "audioWord": "Latitude", "start": 19.32, "end": 19.9, "pageWordId": "p3-1", "matchType": "matched" },
  { "audioWord": "measured", "start": 19.9, "end": 20.42, "pageWordId": "p3-2", "matchType": "matched" },
  { "audioWord": "distance", "start": 20.42, "end": 21.08, "pageWordId": "p3-3", "matchType": "matched" },
  { "audioWord": "north", "start": 21.08, "end": 21.48, "pageWordId": "p3-4", "matchType": "matched" },
  { "audioWord": "-south,", "start": 21.48, "end": 22.0, "pageWordId": "p3-4", "matchType": "matched" },
  { "audioWord": "longitude", "start": 22.36, "end": 22.94, "pageWordId": "p3-5", "matchType": "matched" },
  { "audioWord": "measures", "start": 22.94, "end": 23.46, "pageWordId": "p3-6", "matchType": "matched" },
  { "audioWord": "it", "start": 23.46, "end": 23.8, "pageWordId": "p3-7", "matchType": "matched" },
  { "audioWord": "east", "start": 23.8, "end": 24.1, "pageWordId": "p3-8", "matchType": "matched" },
  { "audioWord": "-west.", "start": 24.1, "end": 24.32, "pageWordId": "p3-8", "matchType": "matched" }
];
