export const PAGE59_TRANSCRIPT = [
  // h: "Western & Eastern Hemispheres"
  { "audioWord": "western", "start": 0.0, "end": 0.5, "pageWordId": "h-1", "matchType": "matched" },
  { "audioWord": "and", "start": 0.5, "end": 0.72, "pageWordId": "h-2", "matchType": "matched" },
  { "audioWord": "eastern", "start": 0.72, "end": 1.08, "pageWordId": "h-3", "matchType": "matched" },
  { "audioWord": "hemispheres.", "start": 1.08, "end": 1.94, "pageWordId": "h-4", "matchType": "matched" },

  // p1: "Cut the globe along the **Prime** **Meridian** **(0°)** and the **180°** line, and it falls into two halves that we can see **fully**."
  { "audioWord": "Cut", "start": 2.54, "end": 2.7, "pageWordId": "p1-1", "matchType": "matched" },
  { "audioWord": "the", "start": 2.7, "end": 2.9, "pageWordId": "p1-2", "matchType": "matched" },
  { "audioWord": "globe", "start": 2.9, "end": 3.1, "pageWordId": "p1-3", "matchType": "matched" },
  { "audioWord": "along", "start": 3.1, "end": 3.42, "pageWordId": "p1-4", "matchType": "matched" },
  { "audioWord": "the", "start": 3.42, "end": 3.7, "pageWordId": "p1-5", "matchType": "matched" },
  { "audioWord": "prime", "start": 3.7, "end": 3.84, "pageWordId": "p1-6", "matchType": "matched" },
  { "audioWord": "meridian,", "start": 3.84, "end": 4.36, "pageWordId": "p1-7", "matchType": "matched" },
  { "audioWord": "0", "start": 4.86, "end": 5.08, "pageWordId": "p1-8", "matchType": "matched" },
  { "audioWord": "degrees,", "start": 5.08, "end": 5.6, "pageWordId": "p1-8", "matchType": "matched" },
  { "audioWord": "and", "start": 5.98, "end": 6.22, "pageWordId": "p1-9", "matchType": "matched" },
  { "audioWord": "the", "start": 6.22, "end": 6.44, "pageWordId": "p1-10", "matchType": "matched" },
  { "audioWord": "180", "start": 6.44, "end": 7.14, "pageWordId": "p1-11", "matchType": "matched" },
  { "audioWord": "degrees", "start": 7.14, "end": 7.64, "pageWordId": "p1-11", "matchType": "matched" },
  { "audioWord": "line,", "start": 7.64, "end": 8.02, "pageWordId": "p1-12", "matchType": "matched" },
  { "audioWord": "and", "start": 8.4, "end": 8.64, "pageWordId": "p1-13", "matchType": "matched" },
  { "audioWord": "it", "start": 8.64, "end": 8.84, "pageWordId": "p1-14", "matchType": "matched" },
  { "audioWord": "falls", "start": 8.84, "end": 9.18, "pageWordId": "p1-15", "matchType": "matched" },
  { "audioWord": "into", "start": 9.18, "end": 9.62, "pageWordId": "p1-16", "matchType": "matched" },
  { "audioWord": "two", "start": 9.62, "end": 9.96, "pageWordId": "p1-17", "matchType": "matched" },
  { "audioWord": "halves", "start": 9.96, "end": 10.3, "pageWordId": "p1-18", "matchType": "matched" },
  { "audioWord": "that", "start": 10.3, "end": 10.84, "pageWordId": "p1-19", "matchType": "matched" },
  { "audioWord": "we", "start": 10.84, "end": 11.02, "pageWordId": "p1-20", "matchType": "matched" },
  { "audioWord": "can", "start": 11.02, "end": 11.24, "pageWordId": "p1-21", "matchType": "matched" },
  { "audioWord": "see", "start": 11.24, "end": 11.46, "pageWordId": "p1-22", "matchType": "matched" },
  { "audioWord": "fully.", "start": 11.46, "end": 11.8, "pageWordId": "p1-23", "matchType": "matched" },

  // p2: "The left half (blue) is the **Western** **Hemisphere** (0°–180° West); the right half (orange) is the **Eastern** **Hemisphere** (0°–180° East). India lies in the Eastern Hemisphere."
  { "audioWord": "The", "start": 12.68, "end": 12.84, "pageWordId": "p2-1", "matchType": "matched" },
  { "audioWord": "left", "start": 12.84, "end": 13.04, "pageWordId": "p2-2", "matchType": "matched" },
  { "audioWord": "half", "start": 13.04, "end": 13.32, "pageWordId": "p2-3", "matchType": "matched" },
  { "audioWord": "is", "start": 13.32, "end": 13.66, "pageWordId": "p2-5", "matchType": "matched" },
  { "audioWord": "the", "start": 13.66, "end": 13.8, "pageWordId": "p2-6", "matchType": "matched" },
  { "audioWord": "western", "start": 13.8, "end": 14.08, "pageWordId": "p2-7", "matchType": "matched" },
  { "audioWord": "hemisphere,", "start": 14.08, "end": 14.64, "pageWordId": "p2-8", "matchType": "matched" },
  { "audioWord": "0", "start": 15.18, "end": 15.44, "pageWordId": "p2-9", "matchType": "matched" },
  { "audioWord": "degrees", "start": 15.44, "end": 15.9, "pageWordId": "p2-9", "matchType": "matched" },
  { "audioWord": "to", "start": 15.9, "end": 16.2, "pageWordId": "p2-9", "matchType": "matched" },
  { "audioWord": "180", "start": 16.2, "end": 16.86, "pageWordId": "p2-9", "matchType": "matched" },
  { "audioWord": "degrees", "start": 16.86, "end": 17.4, "pageWordId": "p2-9", "matchType": "matched" },
  { "audioWord": "west.", "start": 17.4, "end": 17.78, "pageWordId": "p2-10", "matchType": "matched" },
  { "audioWord": "The", "start": 17.78, "end": 18.82, "pageWordId": "p2-11", "matchType": "matched" },
  { "audioWord": "right", "start": 18.82, "end": 19.12, "pageWordId": "p2-12", "matchType": "matched" },
  { "audioWord": "half", "start": 19.12, "end": 19.36, "pageWordId": "p2-13", "matchType": "matched" },
  { "audioWord": "is", "start": 19.36, "end": 19.68, "pageWordId": "p2-15", "matchType": "matched" },
  { "audioWord": "the", "start": 19.68, "end": 19.92, "pageWordId": "p2-16", "matchType": "matched" },
  { "audioWord": "eastern", "start": 19.92, "end": 20.2, "pageWordId": "p2-17", "matchType": "matched" },
  { "audioWord": "hemisphere,", "start": 20.2, "end": 20.76, "pageWordId": "p2-18", "matchType": "matched" },
  { "audioWord": "0", "start": 21.44, "end": 21.58, "pageWordId": "p2-19", "matchType": "matched" },
  { "audioWord": "degrees", "start": 21.58, "end": 22.02, "pageWordId": "p2-19", "matchType": "matched" },
  { "audioWord": "to", "start": 22.02, "end": 22.28, "pageWordId": "p2-19", "matchType": "matched" },
  { "audioWord": "180", "start": 22.28, "end": 23.06, "pageWordId": "p2-19", "matchType": "matched" },
  { "audioWord": "degrees", "start": 23.06, "end": 23.6, "pageWordId": "p2-19", "matchType": "matched" },
  { "audioWord": "east.", "start": 23.6, "end": 23.92, "pageWordId": "p2-20", "matchType": "matched" }
];
