export const PAGE46_TRANSCRIPT = [
  // Title: "The North & South Poles"
  { "audioWord": "The", "start": 0.0, "end": 0.24, "pageWordId": "h-1", "matchType": "matched" },
  { "audioWord": "north", "start": 0.24, "end": 0.54, "pageWordId": "h-2", "matchType": "matched" },
  { "audioWord": "and", "start": 0.54, "end": 0.7, "pageWordId": "h-3", "matchType": "matched" },
  { "audioWord": "south", "start": 0.7, "end": 1.04, "pageWordId": "h-4", "matchType": "matched" },
  { "audioWord": "poles", "start": 1.04, "end": 1.38, "pageWordId": "h-5", "matchType": "matched" },

  // p1: "Rotate the globe and two points stay fixed — one at the very top and one at the very bottom. These are the North Pole and the South Pole."
  { "audioWord": "rotate", "start": 1.38, "end": 1.88, "pageWordId": "p1-1", "matchType": "matched" },
  { "audioWord": "the", "start": 1.88, "end": 2.16, "pageWordId": "p1-2", "matchType": "matched" },
  { "audioWord": "globe", "start": 2.16, "end": 2.36, "pageWordId": "p1-3", "matchType": "matched" },
  { "audioWord": "and", "start": 2.36, "end": 3.02, "pageWordId": "p1-4", "matchType": "matched" },
  { "audioWord": "two", "start": 3.02, "end": 3.3, "pageWordId": "p1-5", "matchType": "matched" },
  { "audioWord": "points", "start": 3.3, "end": 3.66, "pageWordId": "p1-6", "matchType": "matched" },
  { "audioWord": "stay", "start": 3.66, "end": 3.98, "pageWordId": "p1-7", "matchType": "matched" },
  { "audioWord": "fixed,", "start": 3.98, "end": 4.44, "pageWordId": "p1-8", "matchType": "matched" },
  { "audioWord": "—", "start": 5.08, "end": 5.08, "pageWordId": "p1-9", "matchType": "unmatched" },
  { "audioWord": "one", "start": 5.08, "end": 5.26, "pageWordId": "p1-10", "matchType": "matched" },
  { "audioWord": "at", "start": 5.26, "end": 5.44, "pageWordId": "p1-11", "matchType": "matched" },
  { "audioWord": "the", "start": 5.44, "end": 5.52, "pageWordId": "p1-12", "matchType": "matched" },
  { "audioWord": "very", "start": 5.52, "end": 5.82, "pageWordId": "p1-13", "matchType": "matched" },
  { "audioWord": "top", "start": 5.82, "end": 6.1, "pageWordId": "p1-14", "matchType": "matched" },
  { "audioWord": "and", "start": 6.1, "end": 6.56, "pageWordId": "p1-15", "matchType": "matched" },
  { "audioWord": "one", "start": 6.56, "end": 6.86, "pageWordId": "p1-16", "matchType": "matched" },
  { "audioWord": "at", "start": 6.86, "end": 7.12, "pageWordId": "p1-17", "matchType": "matched" },
  { "audioWord": "the", "start": 7.12, "end": 7.24, "pageWordId": "p1-18", "matchType": "matched" },
  { "audioWord": "very", "start": 7.24, "end": 7.48, "pageWordId": "p1-19", "matchType": "matched" },
  { "audioWord": "bottom.", "start": 7.48, "end": 7.82, "pageWordId": "p1-20", "matchType": "matched" },
  { "audioWord": "These", "start": 8.54, "end": 8.82, "pageWordId": "p1-21", "matchType": "matched" },
  { "audioWord": "are", "start": 8.82, "end": 9.02, "pageWordId": "p1-22", "matchType": "matched" },
  { "audioWord": "the", "start": 9.02, "end": 9.18, "pageWordId": "p1-23", "matchType": "matched" },
  { "audioWord": "north", "start": 9.18, "end": 9.48, "pageWordId": "p1-24", "matchType": "matched" },
  { "audioWord": "pole", "start": 9.48, "end": 9.84, "pageWordId": "p1-25", "matchType": "matched" },
  { "audioWord": "and", "start": 9.84, "end": 10.16, "pageWordId": "p1-26", "matchType": "matched" },
  { "audioWord": "the", "start": 10.16, "end": 10.38, "pageWordId": "p1-27", "matchType": "matched" },
  { "audioWord": "south", "start": 10.38, "end": 10.6, "pageWordId": "p1-28", "matchType": "matched" },
  { "audioWord": "pole.", "start": 10.6, "end": 10.96, "pageWordId": "p1-29", "matchType": "matched" },

  // p2: "The Earth spins around an imaginary rod that joins them, called its axis (shown in gold). The poles are our starting references for every other line."
  { "audioWord": "The", "start": 11.88, "end": 12.04, "pageWordId": "p2-1", "matchType": "matched" },
  { "audioWord": "earth", "start": 12.04, "end": 12.2, "pageWordId": "p2-2", "matchType": "matched" },
  { "audioWord": "spins", "start": 12.2, "end": 12.62, "pageWordId": "p2-3", "matchType": "matched" },
  { "audioWord": "around", "start": 12.62, "end": 13.06, "pageWordId": "p2-4", "matchType": "matched" },
  { "audioWord": "an", "start": 13.06, "end": 13.56, "pageWordId": "p2-5", "matchType": "matched" },
  { "audioWord": "imaginary", "start": 13.56, "end": 14.02, "pageWordId": "p2-6", "matchType": "matched" },
  { "audioWord": "rod", "start": 14.02, "end": 14.38, "pageWordId": "p2-7", "matchType": "matched" },
  { "audioWord": "that", "start": 14.38, "end": 14.7, "pageWordId": "p2-8", "matchType": "matched" },
  { "audioWord": "joins", "start": 14.7, "end": 14.96, "pageWordId": "p2-9", "matchType": "matched" },
  { "audioWord": "them,", "start": 14.96, "end": 15.42, "pageWordId": "p2-10", "matchType": "matched" },
  { "audioWord": "called", "start": 15.74, "end": 15.88, "pageWordId": "p2-11", "matchType": "matched" },
  { "audioWord": "its", "start": 15.88, "end": 16.22, "pageWordId": "p2-12", "matchType": "matched" },
  { "audioWord": "axis,", "start": 16.22, "end": 16.74, "pageWordId": "p2-13", "matchType": "matched" },
  { "audioWord": "(shown", "start": 17.3, "end": 17.3, "pageWordId": "p2-14", "matchType": "unmatched" },
  { "audioWord": "in", "start": 17.54, "end": 17.96, "pageWordId": "p2-15", "matchType": "matched" },
  { "audioWord": "gold).", "start": 17.96, "end": 18.22, "pageWordId": "p2-16", "matchType": "matched" },
  { "audioWord": "The", "start": 18.22, "end": 19.42, "pageWordId": "p2-17", "matchType": "matched" },
  { "audioWord": "poles", "start": 19.42, "end": 19.8, "pageWordId": "p2-18", "matchType": "matched" },
  { "audioWord": "are", "start": 19.8, "end": 20.32, "pageWordId": "p2-19", "matchType": "matched" },
  { "audioWord": "our", "start": 20.32, "end": 20.64, "pageWordId": "p2-20", "matchType": "matched" },
  { "audioWord": "starting", "start": 20.64, "end": 20.98, "pageWordId": "p2-21", "matchType": "matched" },
  { "audioWord": "references", "start": 20.98, "end": 21.5, "pageWordId": "p2-22", "matchType": "matched" },
  { "audioWord": "for", "start": 21.5, "end": 21.94, "pageWordId": "p2-23", "matchType": "matched" },
  { "audioWord": "every", "start": 21.94, "end": 22.22, "pageWordId": "p2-24", "matchType": "matched" },
  { "audioWord": "other", "start": 22.22, "end": 22.48, "pageWordId": "p2-25", "matchType": "matched" },
  { "audioWord": "line.", "start": 22.48, "end": 22.72, "pageWordId": "p2-26", "matchType": "matched" }
];
