export const PAGE57_TRANSCRIPT = [
  // h: "Finding Any Place"
  { "audioWord": "finding", "start": 0.0, "end": 0.44, "pageWordId": "h-1", "matchType": "matched" },
  { "audioWord": "any", "start": 0.44, "end": 0.82, "pageWordId": "h-2", "matchType": "matched" },
  { "audioWord": "place,", "start": 0.82, "end": 1.26, "pageWordId": "h-3", "matchType": "matched" },

  // p1: "Put the parallels and the meridians together and they form a complete net — the **global** **grid**, or **graticule**. Every place now sits where one line of latitude **crosses** one line of longitude."
  { "audioWord": "put", "start": 1.92, "end": 2.16, "pageWordId": "p1-1", "matchType": "matched" },
  { "audioWord": "the", "start": 2.16, "end": 2.44, "pageWordId": "p1-2", "matchType": "matched" },
  { "audioWord": "parallels", "start": 2.44, "end": 2.72, "pageWordId": "p1-3", "matchType": "matched" },
  { "audioWord": "and", "start": 2.72, "end": 2.98, "pageWordId": "p1-4", "matchType": "matched" },
  { "audioWord": "the", "start": 2.98, "end": 3.1, "pageWordId": "p1-5", "matchType": "matched" },
  { "audioWord": "meridians", "start": 3.1, "end": 3.48, "pageWordId": "p1-6", "matchType": "matched" },
  { "audioWord": "together", "start": 3.48, "end": 4.02, "pageWordId": "p1-7", "matchType": "matched" },
  { "audioWord": "and", "start": 4.02, "end": 4.5, "pageWordId": "p1-8", "matchType": "matched" },
  { "audioWord": "they", "start": 4.5, "end": 4.76, "pageWordId": "p1-9", "matchType": "matched" },
  { "audioWord": "form", "start": 4.76, "end": 5.08, "pageWordId": "p1-10", "matchType": "matched" },
  { "audioWord": "a", "start": 5.08, "end": 5.48, "pageWordId": "p1-11", "matchType": "matched" },
  { "audioWord": "complete", "start": 5.48, "end": 5.9, "pageWordId": "p1-12", "matchType": "matched" },
  { "audioWord": "net,", "start": 5.9, "end": 6.2, "pageWordId": "p1-13", "matchType": "matched" },
  { "audioWord": "the", "start": 6.82, "end": 7.04, "pageWordId": "p1-15", "matchType": "matched" },
  { "audioWord": "global", "start": 7.04, "end": 7.34, "pageWordId": "p1-16", "matchType": "matched" },
  { "audioWord": "grid", "start": 7.34, "end": 7.72, "pageWordId": "p1-17", "matchType": "matched" },
  { "audioWord": "or", "start": 7.72, "end": 8.32, "pageWordId": "p1-18", "matchType": "matched" },
  { "audioWord": "graticule.", "start": 8.32, "end": 9.48, "pageWordId": "p1-19", "matchType": "matched" },
  { "audioWord": "Every", "start": 9.68, "end": 10.04, "pageWordId": "p1-20", "matchType": "matched" },
  { "audioWord": "place", "start": 10.04, "end": 10.36, "pageWordId": "p1-21", "matchType": "matched" },
  { "audioWord": "now", "start": 10.36, "end": 10.74, "pageWordId": "p1-22", "matchType": "matched" },
  { "audioWord": "sits", "start": 10.74, "end": 11.06, "pageWordId": "p1-23", "matchType": "matched" },
  { "audioWord": "where", "start": 11.06, "end": 11.64, "pageWordId": "p1-24", "matchType": "matched" },
  { "audioWord": "one", "start": 11.64, "end": 11.98, "pageWordId": "p1-25", "matchType": "matched" },
  { "audioWord": "line", "start": 11.98, "end": 12.24, "pageWordId": "p1-26", "matchType": "matched" },
  { "audioWord": "of", "start": 12.24, "end": 12.46, "pageWordId": "p1-27", "matchType": "matched" },
  { "audioWord": "latitude", "start": 12.46, "end": 13.02, "pageWordId": "p1-28", "matchType": "matched" },
  { "audioWord": "crosses", "start": 13.02, "end": 13.72, "pageWordId": "p1-29", "matchType": "matched" },
  { "audioWord": "one", "start": 13.72, "end": 14.16, "pageWordId": "p1-30", "matchType": "matched" },
  { "audioWord": "line", "start": 14.16, "end": 14.52, "pageWordId": "p1-31", "matchType": "matched" },
  { "audioWord": "of", "start": 14.52, "end": 14.84, "pageWordId": "p1-32", "matchType": "matched" },
  { "audioWord": "longitude.", "start": 14.84, "end": 15.42, "pageWordId": "p1-33", "matchType": "matched" },

  // p2: "We give its **latitude** **first**, then its **longitude**. For example, **New** **Delhi** is **28.6°N,** **77.2°E** — a single, exact address."
  { "audioWord": "We", "start": 15.92, "end": 16.12, "pageWordId": "p2-1", "matchType": "matched" },
  { "audioWord": "give", "start": 16.12, "end": 16.28, "pageWordId": "p2-2", "matchType": "matched" },
  { "audioWord": "its", "start": 16.28, "end": 16.52, "pageWordId": "p2-3", "matchType": "matched" },
  { "audioWord": "latitude", "start": 16.52, "end": 17.02, "pageWordId": "p2-4", "matchType": "matched" },
  { "audioWord": "first,", "start": 17.02, "end": 17.52, "pageWordId": "p2-5", "matchType": "matched" },
  { "audioWord": "then", "start": 17.88, "end": 18.18, "pageWordId": "p2-6", "matchType": "matched" },
  { "audioWord": "its", "start": 18.18, "end": 18.48, "pageWordId": "p2-7", "matchType": "matched" },
  { "audioWord": "longitude.", "start": 18.48, "end": 19.2, "pageWordId": "p2-8", "matchType": "matched" },
  { "audioWord": "For", "start": 19.56, "end": 19.78, "pageWordId": "p2-9", "matchType": "matched" },
  { "audioWord": "example,", "start": 19.78, "end": 20.34, "pageWordId": "p2-10", "matchType": "matched" },
  { "audioWord": "New", "start": 20.84, "end": 21.0, "pageWordId": "p2-11", "matchType": "matched" },
  { "audioWord": "Delhi", "start": 21.0, "end": 21.28, "pageWordId": "p2-12", "matchType": "matched" },
  { "audioWord": "is", "start": 21.28, "end": 21.62, "pageWordId": "p2-13", "matchType": "matched" },
  { "audioWord": "28", "start": 21.62, "end": 22.14, "pageWordId": "p2-14", "matchType": "matched" },
  { "audioWord": ".6", "start": 22.14, "end": 22.9, "pageWordId": "p2-14", "matchType": "matched" },
  { "audioWord": "degrees", "start": 22.9, "end": 23.3, "pageWordId": "p2-14", "matchType": "matched" },
  { "audioWord": "north,", "start": 23.3, "end": 23.84, "pageWordId": "p2-14", "matchType": "matched" },
  { "audioWord": "77", "start": 24.22, "end": 24.64, "pageWordId": "p2-15", "matchType": "matched" },
  { "audioWord": ".2", "start": 24.64, "end": 25.38, "pageWordId": "p2-15", "matchType": "matched" },
  { "audioWord": "degrees", "start": 25.38, "end": 25.7, "pageWordId": "p2-15", "matchType": "matched" },
  { "audioWord": "east,", "start": 25.7, "end": 26.14, "pageWordId": "p2-15", "matchType": "matched" },
  { "audioWord": "a", "start": 26.6, "end": 26.84, "pageWordId": "p2-17", "matchType": "matched" },
  { "audioWord": "single", "start": 26.84, "end": 27.26, "pageWordId": "p2-18", "matchType": "matched" },
  { "audioWord": "exact", "start": 27.26, "end": 28.06, "pageWordId": "p2-19", "matchType": "matched" },
  { "audioWord": "address.", "start": 28.06, "end": 28.52, "pageWordId": "p2-20", "matchType": "matched" }
];
