export const PAGE42_TRANSCRIPT = [
  // Title (prefix: t)
  { "audioWord": "Understanding", "start": 0.0, "end": 0.76, "pageWordId": "t-1", "matchType": "matched" },
  { "audioWord": "Coordinates", "start": 0.76, "end": 1.92, "pageWordId": "t-2", "matchType": "matched" },

  // H3 (prefix: h)
  { "audioWord": "Finding", "start": 1.92, "end": 2.38, "pageWordId": "h-1", "matchType": "matched" },
  { "audioWord": "the", "start": 2.38, "end": 2.72, "pageWordId": "h-2", "matchType": "matched" },
  { "audioWord": "exact", "start": 2.72, "end": 3.06, "pageWordId": "h-3", "matchType": "matched" },
  { "audioWord": "spot", "start": 3.06, "end": 3.54, "pageWordId": "h-4", "matchType": "matched" },

  // P1 (prefix: p1)
  { "audioWord": "Imagine", "start": 3.54, "end": 4.48, "pageWordId": "p1-1", "matchType": "matched" },
  { "audioWord": "trying", "start": 4.48, "end": 5.04, "pageWordId": "p1-2", "matchType": "matched" },
  { "audioWord": "to", "start": 5.04, "end": 5.24, "pageWordId": "p1-3", "matchType": "matched" },
  { "audioWord": "find", "start": 5.24, "end": 5.44, "pageWordId": "p1-4", "matchType": "matched" },
  { "audioWord": "a", "start": 5.44, "end": 5.66, "pageWordId": "p1-5", "matchType": "matched" },
  { "audioWord": "friend's", "start": 5.66, "end": 5.9, "pageWordId": "p1-6", "matchType": "matched" },
  { "audioWord": "house", "start": 5.9, "end": 6.14, "pageWordId": "p1-7", "matchType": "matched" },
  { "audioWord": "in", "start": 6.14, "end": 6.34, "pageWordId": "p1-8", "matchType": "matched" },
  { "audioWord": "a", "start": 6.34, "end": 6.48, "pageWordId": "p1-9", "matchType": "matched" },
  { "audioWord": "large", "start": 6.48, "end": 6.72, "pageWordId": "p1-10", "matchType": "matched" },
  { "audioWord": "city", "start": 6.72, "end": 7.04, "pageWordId": "p1-11", "matchType": "matched" },
  { "audioWord": "built", "start": 7.04, "end": 7.36, "pageWordId": "p1-12", "matchType": "matched" },
  { "audioWord": "on", "start": 7.36, "end": 7.6, "pageWordId": "p1-13", "matchType": "matched" },
  { "audioWord": "a", "start": 7.6, "end": 7.74, "pageWordId": "p1-14", "matchType": "matched" },
  { "audioWord": "grid.", "start": 7.74, "end": 7.9, "pageWordId": "p1-15", "matchType": "matched" },
  { "audioWord": "If", "start": 8.52, "end": 8.6, "pageWordId": "p1-16", "matchType": "matched" },
  { "audioWord": "they", "start": 8.6, "end": 8.8, "pageWordId": "p1-17", "matchType": "matched" },
  { "audioWord": "tell", "start": 8.8, "end": 9.04, "pageWordId": "p1-18", "matchType": "matched" },
  { "audioWord": "you,", "start": 9.04, "end": 9.56, "pageWordId": "p1-19", "matchType": "matched" },
  { "audioWord": "meet", "start": 9.7, "end": 9.8, "pageWordId": "p1-20", "matchType": "matched" },
  { "audioWord": "me", "start": 9.8, "end": 10.02, "pageWordId": "p1-21", "matchType": "matched" },
  { "audioWord": "at", "start": 10.02, "end": 10.12, "pageWordId": "p1-22", "matchType": "matched" },
  { "audioWord": "the", "start": 10.12, "end": 10.32, "pageWordId": "p1-23", "matchType": "matched" },
  { "audioWord": "corner", "start": 10.32, "end": 10.52, "pageWordId": "p1-24", "matchType": "matched" },
  { "audioWord": "of", "start": 10.52, "end": 10.76, "pageWordId": "p1-25", "matchType": "matched" },
  { "audioWord": "5th", "start": 10.76, "end": 11.1, "pageWordId": "p1-26", "matchType": "matched" },
  { "audioWord": "Avenue", "start": 11.1, "end": 11.36, "pageWordId": "p1-27", "matchType": "matched" },
  { "audioWord": "and", "start": 11.36, "end": 11.54, "pageWordId": "p1-28", "matchType": "matched" },
  { "audioWord": "42nd", "start": 11.54, "end": 12.2, "pageWordId": "p1-29", "matchType": "matched" },
  { "audioWord": "Street,", "start": 12.2, "end": 12.64, "pageWordId": "p1-30", "matchType": "matched" },
  { "audioWord": "you", "start": 13.08, "end": 13.28, "pageWordId": "p1-31", "matchType": "matched" },
  { "audioWord": "know", "start": 13.28, "end": 13.5, "pageWordId": "p1-32", "matchType": "matched" },
  { "audioWord": "exactly", "start": 13.5, "end": 14.02, "pageWordId": "p1-33", "matchType": "matched" },
  { "audioWord": "where", "start": 14.02, "end": 14.24, "pageWordId": "p1-34", "matchType": "matched" },
  { "audioWord": "to", "start": 14.24, "end": 14.42, "pageWordId": "p1-35", "matchType": "matched" },
  { "audioWord": "go.", "start": 14.42, "end": 14.68, "pageWordId": "p1-36", "matchType": "matched" },

  // P2 (prefix: p2)
  { "audioWord": "By", "start": 15.24, "end": 15.48, "pageWordId": "p2-1", "matchType": "matched" },
  { "audioWord": "finding", "start": 15.48, "end": 15.88, "pageWordId": "p2-2", "matchType": "matched" },
  { "audioWord": "where", "start": 15.88, "end": 16.12, "pageWordId": "p2-3", "matchType": "matched" },
  { "audioWord": "those", "start": 16.12, "end": 16.44, "pageWordId": "p2-4", "matchType": "matched" },
  { "audioWord": "two", "start": 16.44, "end": 16.66, "pageWordId": "p2-5", "matchType": "matched" },
  { "audioWord": "specific", "start": 16.66, "end": 17.12, "pageWordId": "p2-6", "matchType": "matched" },
  { "audioWord": "streets", "start": 17.12, "end": 17.48, "pageWordId": "p2-7", "matchType": "matched" },
  { "audioWord": "cross", "start": 17.48, "end": 17.84, "pageWordId": "p2-8", "matchType": "matched" },
  { "audioWord": "each", "start": 17.84, "end": 18.1, "pageWordId": "p2-9", "matchType": "matched" },
  { "audioWord": "other", "start": 18.1, "end": 18.36, "pageWordId": "p2-10", "matchType": "matched" },
  { "audioWord": "on", "start": 18.36, "end": 18.6, "pageWordId": "p2-11", "matchType": "matched" },
  { "audioWord": "a", "start": 18.6, "end": 18.74, "pageWordId": "p2-12", "matchType": "matched" },
  { "audioWord": "map,", "start": 18.74, "end": 19.0, "pageWordId": "p2-13", "matchType": "matched" },
  { "audioWord": "you", "start": 19.48, "end": 19.52, "pageWordId": "p2-14", "matchType": "matched" },
  { "audioWord": "can", "start": 19.52, "end": 19.76, "pageWordId": "p2-15", "matchType": "matched" },
  { "audioWord": "pinpoint", "start": 19.76, "end": 20.22, "pageWordId": "p2-16", "matchType": "matched" },
  { "audioWord": "the", "start": 20.22, "end": 20.6, "pageWordId": "p2-17", "matchType": "matched" },
  { "audioWord": "exact", "start": 20.6, "end": 20.96, "pageWordId": "p2-18", "matchType": "matched" },
  { "audioWord": "intersection", "start": 20.96, "end": 21.52, "pageWordId": "p2-19", "matchType": "matched" },
  { "audioWord": "instantly", "start": 21.52, "end": 22.18, "pageWordId": "p2-20", "matchType": "matched" },
  { "audioWord": "without", "start": 22.18, "end": 22.68, "pageWordId": "p2-21", "matchType": "matched" },
  { "audioWord": "getting", "start": 22.68, "end": 23.0, "pageWordId": "p2-22", "matchType": "matched" },
  { "audioWord": "lost.", "start": 23.0, "end": 23.44, "pageWordId": "p2-23", "matchType": "matched" },

  // P3 (prefix: p3)
  { "audioWord": "To", "start": 23.98, "end": 24.16, "pageWordId": "p3-1", "matchType": "matched" },
  { "audioWord": "locate", "start": 24.16, "end": 24.46, "pageWordId": "p3-2", "matchType": "matched" },
  { "audioWord": "any", "start": 24.46, "end": 24.78, "pageWordId": "p3-3", "matchType": "matched" },
  { "audioWord": "place", "start": 24.78, "end": 25.14, "pageWordId": "p3-4", "matchType": "matched" },
  { "audioWord": "precisely", "start": 25.14, "end": 25.7, "pageWordId": "p3-5", "matchType": "matched" },
  { "audioWord": "on", "start": 25.7, "end": 25.98, "pageWordId": "p3-6", "matchType": "matched" },
  { "audioWord": "earth,", "start": 25.98, "end": 26.16, "pageWordId": "p3-7", "matchType": "matched" },
  { "audioWord": "we", "start": 26.62, "end": 26.76, "pageWordId": "p3-8", "matchType": "matched" },
  { "audioWord": "also", "start": 26.76, "end": 27.06, "pageWordId": "p3-9", "matchType": "matched" },
  { "audioWord": "use", "start": 27.06, "end": 27.3, "pageWordId": "p3-10", "matchType": "matched" },
  { "audioWord": "a", "start": 27.3, "end": 27.52, "pageWordId": "p3-11", "matchType": "matched" },
  { "audioWord": "giant", "start": 27.52, "end": 27.74, "pageWordId": "p3-12", "matchType": "matched" },
  { "audioWord": "grid", "start": 27.74, "end": 28.02, "pageWordId": "p3-13", "matchType": "matched" },
  { "audioWord": "and", "start": 28.02, "end": 28.52, "pageWordId": "p3-14", "matchType": "matched" },
  { "audioWord": "always", "start": 28.52, "end": 29.0, "pageWordId": "p3-15", "matchType": "matched" },
  { "audioWord": "need", "start": 29.0, "end": 29.3, "pageWordId": "p3-16", "matchType": "matched" },
  { "audioWord": "two", "start": 29.3, "end": 29.56, "pageWordId": "p3-17", "matchType": "matched" },
  { "audioWord": "pieces", "start": 29.56, "end": 29.86, "pageWordId": "p3-18", "matchType": "matched" },
  { "audioWord": "of", "start": 29.86, "end": 30.16, "pageWordId": "p3-19", "matchType": "matched" },
  { "audioWord": "information", "start": 30.16, "end": 30.64, "pageWordId": "p3-20", "matchType": "matched" },
  { "audioWord": "to", "start": 30.64, "end": 31.02, "pageWordId": "p3-21", "matchType": "matched" },
  { "audioWord": "form", "start": 31.02, "end": 31.16, "pageWordId": "p3-22", "matchType": "matched" },
  { "audioWord": "a", "start": 31.16, "end": 31.36, "pageWordId": "p3-23", "matchType": "matched" },
  { "audioWord": "coordinate.", "start": 31.36, "end": 31.74, "pageWordId": "p3-24", "matchType": "matched" }
];
