export const PAGE49_TRANSCRIPT = [
  // Title: "Parallels of Latitude"
  { "audioWord": "Parallels", "start": 0.0, "end": 0.64, "pageWordId": "h-1", "matchType": "matched" },
  { "audioWord": "of", "start": 0.64, "end": 0.88, "pageWordId": "h-2", "matchType": "matched" },
  { "audioWord": "Latitude", "start": 0.88, "end": 1.48, "pageWordId": "h-3", "matchType": "matched" },

  // p1: "At any point on that journey you can draw an imaginary line running east-west, parallel to the Equator. Such a line is called a parallel of latitude, and it forms a circle around the Earth."
  { "audioWord": "At", "start": 2.0, "end": 2.5, "pageWordId": "p1-1", "matchType": "matched" },
  { "audioWord": "any", "start": 2.5, "end": 2.7, "pageWordId": "p1-2", "matchType": "matched" },
  { "audioWord": "point", "start": 2.7, "end": 2.94, "pageWordId": "p1-3", "matchType": "matched" },
  { "audioWord": "on", "start": 2.94, "end": 3.14, "pageWordId": "p1-4", "matchType": "matched" },
  { "audioWord": "that", "start": 3.14, "end": 3.32, "pageWordId": "p1-5", "matchType": "matched" },
  { "audioWord": "journey,", "start": 3.32, "end": 3.68, "pageWordId": "p1-6", "matchType": "matched" },
  { "audioWord": "you", "start": 4.1, "end": 4.26, "pageWordId": "p1-7", "matchType": "matched" },
  { "audioWord": "can", "start": 4.26, "end": 4.48, "pageWordId": "p1-8", "matchType": "matched" },
  { "audioWord": "draw", "start": 4.48, "end": 4.74, "pageWordId": "p1-9", "matchType": "matched" },
  { "audioWord": "an", "start": 4.74, "end": 5.08, "pageWordId": "p1-10", "matchType": "matched" },
  { "audioWord": "imaginary", "start": 5.08, "end": 5.5, "pageWordId": "p1-11", "matchType": "matched" },
  { "audioWord": "line", "start": 5.5, "end": 5.98, "pageWordId": "p1-12", "matchType": "matched" },
  { "audioWord": "running", "start": 5.98, "end": 6.36, "pageWordId": "p1-13", "matchType": "matched" },
  { "audioWord": "east", "start": 6.36, "end": 6.78, "pageWordId": "p1-14", "matchType": "matched" },
  { "audioWord": "-west,", "start": 6.78, "end": 7.28, "pageWordId": "p1-14", "matchType": "matched" },
  { "audioWord": "parallel", "start": 7.74, "end": 7.88, "pageWordId": "p1-15", "matchType": "matched" },
  { "audioWord": "to", "start": 7.88, "end": 8.14, "pageWordId": "p1-16", "matchType": "matched" },
  { "audioWord": "the", "start": 8.14, "end": 8.34, "pageWordId": "p1-17", "matchType": "matched" },
  { "audioWord": "equator.", "start": 8.34, "end": 8.68, "pageWordId": "p1-18", "matchType": "matched" },
  { "audioWord": "Such", "start": 9.36, "end": 9.58, "pageWordId": "p1-19", "matchType": "matched" },
  { "audioWord": "a", "start": 9.58, "end": 9.76, "pageWordId": "p1-20", "matchType": "matched" },
  { "audioWord": "line", "start": 9.76, "end": 9.9, "pageWordId": "p1-21", "matchType": "matched" },
  { "audioWord": "is", "start": 9.9, "end": 10.14, "pageWordId": "p1-22", "matchType": "matched" },
  { "audioWord": "called", "start": 10.14, "end": 10.4, "pageWordId": "p1-23", "matchType": "matched" },
  { "audioWord": "a", "start": 10.4, "end": 10.7, "pageWordId": "p1-24", "matchType": "matched" },
  { "audioWord": "parallel", "start": 10.7, "end": 10.86, "pageWordId": "p1-25", "matchType": "matched" },
  { "audioWord": "of", "start": 10.86, "end": 11.14, "pageWordId": "p1-26", "matchType": "matched" },
  { "audioWord": "latitude", "start": 11.14, "end": 11.6, "pageWordId": "p1-27", "matchType": "matched" },
  { "audioWord": "and", "start": 11.6, "end": 12.28, "pageWordId": "p1-28", "matchType": "matched" },
  { "audioWord": "it", "start": 12.28, "end": 12.48, "pageWordId": "p1-29", "matchType": "matched" },
  { "audioWord": "forms", "start": 12.48, "end": 12.74, "pageWordId": "p1-30", "matchType": "matched" },
  { "audioWord": "a", "start": 12.74, "end": 13.02, "pageWordId": "p1-31", "matchType": "matched" },
  { "audioWord": "circle", "start": 13.02, "end": 13.24, "pageWordId": "p1-32", "matchType": "matched" },
  { "audioWord": "around", "start": 13.24, "end": 13.62, "pageWordId": "p1-33", "matchType": "matched" },
  { "audioWord": "the", "start": 13.62, "end": 13.86, "pageWordId": "p1-34", "matchType": "matched" },
  { "audioWord": "Earth.", "start": 13.86, "end": 14.06, "pageWordId": "p1-35", "matchType": "matched" },

  // p2: "The Equator is the largest of these circles; the parallels grow smaller as we move towards either pole."
  { "audioWord": "The", "start": 14.8, "end": 15.02, "pageWordId": "p2-1", "matchType": "matched" },
  { "audioWord": "equator", "start": 15.02, "end": 15.4, "pageWordId": "p2-2", "matchType": "matched" },
  { "audioWord": "is", "start": 15.4, "end": 15.76, "pageWordId": "p2-3", "matchType": "matched" },
  { "audioWord": "the", "start": 15.76, "end": 15.98, "pageWordId": "p2-4", "matchType": "matched" },
  { "audioWord": "largest", "start": 15.98, "end": 16.26, "pageWordId": "p2-5", "matchType": "matched" },
  { "audioWord": "of", "start": 16.26, "end": 16.46, "pageWordId": "p2-6", "matchType": "matched" },
  { "audioWord": "these", "start": 16.46, "end": 16.66, "pageWordId": "p2-7", "matchType": "matched" },
  { "audioWord": "circles.", "start": 16.66, "end": 17.08, "pageWordId": "p2-8", "matchType": "matched" },
  { "audioWord": "The", "start": 17.64, "end": 17.94, "pageWordId": "p2-9", "matchType": "matched" },
  { "audioWord": "parallels", "start": 17.94, "end": 18.24, "pageWordId": "p2-10", "matchType": "matched" },
  { "audioWord": "grow", "start": 18.24, "end": 18.58, "pageWordId": "p2-11", "matchType": "matched" },
  { "audioWord": "smaller", "start": 18.58, "end": 19.0, "pageWordId": "p2-12", "matchType": "matched" },
  { "audioWord": "as", "start": 19.0, "end": 19.32, "pageWordId": "p2-13", "matchType": "matched" },
  { "audioWord": "we", "start": 19.32, "end": 19.56, "pageWordId": "p2-14", "matchType": "matched" },
  { "audioWord": "move", "start": 19.56, "end": 19.82, "pageWordId": "p2-15", "matchType": "matched" },
  { "audioWord": "towards", "start": 19.82, "end": 20.22, "pageWordId": "p2-16", "matchType": "matched" },
  { "audioWord": "either", "start": 20.22, "end": 20.56, "pageWordId": "p2-17", "matchType": "matched" },
  { "audioWord": "pole.", "start": 20.56, "end": 20.84, "pageWordId": "p2-18", "matchType": "matched" }
];
