export const PAGE47_TRANSCRIPT = [
  // Title: "The Equator"
  { "audioWord": "The", "start": 0.0, "end": 0.34, "pageWordId": "h-1", "matchType": "matched" },
  { "audioWord": "equator,", "start": 0.34, "end": 0.74, "pageWordId": "h-2", "matchType": "matched" },

  // p1: "Exactly halfway between the two poles is a circle that runs right around the middle of the Earth. This is the Equator."
  { "audioWord": "exactly", "start": 1.44, "end": 1.82, "pageWordId": "p1-1", "matchType": "matched" },
  { "audioWord": "half", "start": 1.82, "end": 2.06, "pageWordId": "p1-2", "matchType": "matched" },
  { "audioWord": "way", "start": 2.06, "end": 2.24, "pageWordId": "p1-2", "matchType": "matched" }, // maps to "halfway"
  { "audioWord": "between", "start": 2.24, "end": 2.5, "pageWordId": "p1-3", "matchType": "matched" },
  { "audioWord": "the", "start": 2.5, "end": 2.72, "pageWordId": "p1-4", "matchType": "matched" },
  { "audioWord": "two", "start": 2.72, "end": 2.9, "pageWordId": "p1-5", "matchType": "matched" },
  { "audioWord": "poles,", "start": 2.9, "end": 3.26, "pageWordId": "p1-6", "matchType": "matched" },
  { "audioWord": "is", "start": 3.72, "end": 3.84, "pageWordId": "p1-7", "matchType": "matched" },
  { "audioWord": "a", "start": 3.84, "end": 4.04, "pageWordId": "p1-8", "matchType": "matched" },
  { "audioWord": "circle", "start": 4.04, "end": 4.32, "pageWordId": "p1-9", "matchType": "matched" },
  { "audioWord": "that", "start": 4.32, "end": 4.58, "pageWordId": "p1-10", "matchType": "matched" },
  { "audioWord": "runs", "start": 4.58, "end": 4.88, "pageWordId": "p1-11", "matchType": "matched" },
  { "audioWord": "right", "start": 4.88, "end": 5.28, "pageWordId": "p1-12", "matchType": "matched" },
  { "audioWord": "around", "start": 5.28, "end": 5.62, "pageWordId": "p1-13", "matchType": "matched" },
  { "audioWord": "the", "start": 5.62, "end": 5.8, "pageWordId": "p1-14", "matchType": "matched" },
  { "audioWord": "middle", "start": 5.8, "end": 5.96, "pageWordId": "p1-15", "matchType": "matched" },
  { "audioWord": "of", "start": 5.96, "end": 6.2, "pageWordId": "p1-16", "matchType": "matched" },
  { "audioWord": "the", "start": 6.2, "end": 6.34, "pageWordId": "p1-17", "matchType": "matched" },
  { "audioWord": "earth.", "start": 6.34, "end": 6.5, "pageWordId": "p1-18", "matchType": "matched" },
  { "audioWord": "This", "start": 7.0, "end": 7.22, "pageWordId": "p1-19", "matchType": "matched" },
  { "audioWord": "is", "start": 7.22, "end": 7.44, "pageWordId": "p1-20", "matchType": "matched" },
  { "audioWord": "the", "start": 7.44, "end": 7.62, "pageWordId": "p1-21", "matchType": "matched" },
  { "audioWord": "equator.", "start": 7.62, "end": 7.92, "pageWordId": "p1-22", "matchType": "matched" },

  // p2: "It is the largest circle on the globe and divides the Earth into a Northern half and a Southern half. Its value is 0°."
  { "audioWord": "It", "start": 8.58, "end": 8.68, "pageWordId": "p2-1", "matchType": "matched" },
  { "audioWord": "is", "start": 8.68, "end": 8.88, "pageWordId": "p2-2", "matchType": "matched" },
  { "audioWord": "the", "start": 8.88, "end": 9.06, "pageWordId": "p2-3", "matchType": "matched" },
  { "audioWord": "largest", "start": 9.06, "end": 9.32, "pageWordId": "p2-4", "matchType": "matched" },
  { "audioWord": "circle", "start": 9.32, "end": 9.64, "pageWordId": "p2-5", "matchType": "matched" },
  { "audioWord": "on", "start": 9.64, "end": 9.9, "pageWordId": "p2-6", "matchType": "matched" },
  { "audioWord": "the", "start": 9.9, "end": 10.04, "pageWordId": "p2-7", "matchType": "matched" },
  { "audioWord": "globe", "start": 10.04, "end": 10.24, "pageWordId": "p2-8", "matchType": "matched" },
  { "audioWord": "and", "start": 10.24, "end": 10.9, "pageWordId": "p2-9", "matchType": "matched" },
  { "audioWord": "divides", "start": 10.9, "end": 11.24, "pageWordId": "p2-10", "matchType": "matched" },
  { "audioWord": "the", "start": 11.24, "end": 11.5, "pageWordId": "p2-11", "matchType": "matched" },
  { "audioWord": "earth", "start": 11.5, "end": 11.7, "pageWordId": "p2-12", "matchType": "matched" },
  { "audioWord": "into", "start": 11.7, "end": 12.14, "pageWordId": "p2-13", "matchType": "matched" },
  { "audioWord": "a", "start": 12.14, "end": 12.32, "pageWordId": "p2-14", "matchType": "matched" },
  { "audioWord": "northern", "start": 12.32, "end": 12.58, "pageWordId": "p2-15", "matchType": "matched" },
  { "audioWord": "half", "start": 12.58, "end": 12.96, "pageWordId": "p2-16", "matchType": "matched" },
  { "audioWord": "and", "start": 12.96, "end": 13.56, "pageWordId": "p2-17", "matchType": "matched" },
  { "audioWord": "a", "start": 13.56, "end": 13.72, "pageWordId": "p2-18", "matchType": "matched" },
  { "audioWord": "southern", "start": 13.72, "end": 13.92, "pageWordId": "p2-19", "matchType": "matched" },
  { "audioWord": "half.", "start": 13.92, "end": 14.26, "pageWordId": "p2-20", "matchType": "matched" },
  { "audioWord": "Its", "start": 14.7, "end": 14.9, "pageWordId": "p2-21", "matchType": "matched" },
  { "audioWord": "value", "start": 14.9, "end": 15.24, "pageWordId": "p2-22", "matchType": "matched" },
  { "audioWord": "is", "start": 15.24, "end": 15.44, "pageWordId": "p2-23", "matchType": "matched" },
  { "audioWord": "zero", "start": 15.44, "end": 15.7, "pageWordId": "p2-24", "matchType": "matched" },
  { "audioWord": "degrees.", "start": 15.7, "end": 16.06, "pageWordId": "p2-24", "matchType": "matched" } // Maps "zero degrees." to "0°."
];
