export const PAGE50_TRANSCRIPT = [
  // Title: "Latitude in Degrees"
  { "audioWord": "Latitude", "start": 0.0, "end": 0.8, "pageWordId": "h-1", "matchType": "matched" },
  { "audioWord": "in", "start": 0.8, "end": 1.06, "pageWordId": "h-2", "matchType": "matched" },
  { "audioWord": "degrees.", "start": 1.06, "end": 1.62, "pageWordId": "h-3", "matchType": "matched" },

  // p1: "Latitudes are written in **degrees**. By convention, the Equator is latitude **0°**."
  { "audioWord": "Latitudes", "start": 2.26, "end": 2.7, "pageWordId": "p1-1", "matchType": "matched" },
  { "audioWord": "are", "start": 2.7, "end": 3.0, "pageWordId": "p1-2", "matchType": "matched" },
  { "audioWord": "written", "start": 3.0, "end": 3.3, "pageWordId": "p1-3", "matchType": "matched" },
  { "audioWord": "in", "start": 3.3, "end": 3.66, "pageWordId": "p1-4", "matchType": "matched" },
  { "audioWord": "degrees.", "start": 3.66, "end": 3.98, "pageWordId": "p1-5", "matchType": "matched" },
  { "audioWord": "By", "start": 4.6, "end": 4.84, "pageWordId": "p1-6", "matchType": "matched" },
  { "audioWord": "convention,", "start": 4.84, "end": 5.44, "pageWordId": "p1-7", "matchType": "matched" },
  { "audioWord": "the", "start": 5.84, "end": 6.02, "pageWordId": "p1-8", "matchType": "matched" },
  { "audioWord": "equator", "start": 6.02, "end": 6.36, "pageWordId": "p1-9", "matchType": "matched" },
  { "audioWord": "is", "start": 6.36, "end": 6.74, "pageWordId": "p1-10", "matchType": "matched" },
  { "audioWord": "latitude", "start": 6.74, "end": 7.34, "pageWordId": "p1-11", "matchType": "matched" },
  { "audioWord": "0", "start": 7.34, "end": 8.06, "pageWordId": "p1-12", "matchType": "matched" },
  { "audioWord": "degrees.", "start": 8.06, "end": 8.56, "pageWordId": "p1-12", "matchType": "matched" },

  // p2: "The two poles are the highest latitudes — **90°** **North** and **90°** **South**, written **90°N** and **90°S**. So latitude runs from 0° up to 90° on each side."
  { "audioWord": "The", "start": 9.24, "end": 9.44, "pageWordId": "p2-1", "matchType": "matched" },
  { "audioWord": "two", "start": 9.44, "end": 9.68, "pageWordId": "p2-2", "matchType": "matched" },
  { "audioWord": "poles", "start": 9.68, "end": 10.0, "pageWordId": "p2-3", "matchType": "matched" },
  { "audioWord": "are", "start": 10.0, "end": 10.32, "pageWordId": "p2-4", "matchType": "matched" },
  { "audioWord": "the", "start": 10.32, "end": 10.54, "pageWordId": "p2-5", "matchType": "matched" },
  { "audioWord": "highest", "start": 10.54, "end": 10.82, "pageWordId": "p2-6", "matchType": "matched" },
  { "audioWord": "latitudes,", "start": 10.82, "end": 11.56, "pageWordId": "p2-7", "matchType": "matched" },
  { "audioWord": "90", "start": 12.14, "end": 12.4, "pageWordId": "p2-9", "matchType": "matched" },
  { "audioWord": "degrees", "start": 12.4, "end": 12.86, "pageWordId": "p2-9", "matchType": "matched" },
  { "audioWord": "north", "start": 12.86, "end": 13.26, "pageWordId": "p2-10", "matchType": "matched" },
  { "audioWord": "and", "start": 13.26, "end": 13.76, "pageWordId": "p2-11", "matchType": "matched" },
  { "audioWord": "90", "start": 13.76, "end": 14.12, "pageWordId": "p2-12", "matchType": "matched" },
  { "audioWord": "degrees", "start": 14.12, "end": 14.48, "pageWordId": "p2-12", "matchType": "matched" },
  { "audioWord": "south,", "start": 14.48, "end": 15.02, "pageWordId": "p2-13", "matchType": "matched" },
  { "audioWord": "written", "start": 15.48, "end": 15.8, "pageWordId": "p2-14", "matchType": "matched" },
  { "audioWord": "90", "start": 15.8, "end": 16.34, "pageWordId": "p2-15", "matchType": "matched" },
  { "audioWord": "degrees", "start": 16.34, "end": 16.78, "pageWordId": "p2-15", "matchType": "matched" },
  { "audioWord": "north", "start": 16.78, "end": 17.16, "pageWordId": "p2-15", "matchType": "matched" },
  { "audioWord": "and", "start": 17.16, "end": 17.62, "pageWordId": "p2-16", "matchType": "matched" },
  { "audioWord": "90", "start": 17.62, "end": 17.96, "pageWordId": "p2-17", "matchType": "matched" },
  { "audioWord": "degrees", "start": 17.96, "end": 18.34, "pageWordId": "p2-17", "matchType": "matched" },
  { "audioWord": "south.", "start": 18.34, "end": 18.76, "pageWordId": "p2-17", "matchType": "matched" },
  { "audioWord": "So", "start": 19.3, "end": 19.5, "pageWordId": "p2-18", "matchType": "matched" },
  { "audioWord": "latitude", "start": 19.5, "end": 20.04, "pageWordId": "p2-19", "matchType": "matched" },
  { "audioWord": "runs", "start": 20.04, "end": 20.62, "pageWordId": "p2-20", "matchType": "matched" },
  { "audioWord": "from", "start": 20.62, "end": 21.0, "pageWordId": "p2-21", "matchType": "matched" },
  { "audioWord": "0", "start": 21.0, "end": 21.3, "pageWordId": "p2-22", "matchType": "matched" },
  { "audioWord": "degrees", "start": 21.3, "end": 21.88, "pageWordId": "p2-22", "matchType": "matched" },
  { "audioWord": "up", "start": 21.88, "end": 22.32, "pageWordId": "p2-23", "matchType": "matched" },
  { "audioWord": "to", "start": 22.32, "end": 22.54, "pageWordId": "p2-24", "matchType": "matched" },
  { "audioWord": "90", "start": 22.54, "end": 22.82, "pageWordId": "p2-25", "matchType": "matched" },
  { "audioWord": "degrees", "start": 22.82, "end": 23.3, "pageWordId": "p2-25", "matchType": "matched" },
  { "audioWord": "on", "start": 23.3, "end": 23.54, "pageWordId": "p2-26", "matchType": "matched" },
  { "audioWord": "each", "start": 23.54, "end": 23.78, "pageWordId": "p2-27", "matchType": "matched" },
  { "audioWord": "side.", "start": 23.78, "end": 24.04, "pageWordId": "p2-28", "matchType": "matched" }
];
