export const PAGE52_TRANSCRIPT = [
  // Title: "The Prime Meridian"
  { "audioWord": "The", "start": 0.0, "end": 0.34, "pageWordId": "h-1", "matchType": "matched" },
  { "audioWord": "prime", "start": 0.34, "end": 0.6, "pageWordId": "h-2", "matchType": "matched" },
  { "audioWord": "meridian", "start": 0.6, "end": 0.98, "pageWordId": "h-3", "matchType": "matched" },

  // p1: "Longitude needs a **starting** **line**, just as latitude has the Equator. That line is the **Prime** **Meridian**."
  { "audioWord": "longitude", "start": 0.98, "end": 1.7, "pageWordId": "p1-1", "matchType": "matched" },
  { "audioWord": "needs", "start": 1.7, "end": 2.28, "pageWordId": "p1-2", "matchType": "matched" },
  { "audioWord": "a", "start": 2.28, "end": 2.68, "pageWordId": "p1-3", "matchType": "matched" },
  { "audioWord": "starting", "start": 2.68, "end": 2.9, "pageWordId": "p1-4", "matchType": "matched" },
  { "audioWord": "line,", "start": 2.9, "end": 3.36, "pageWordId": "p1-5", "matchType": "matched" },
  { "audioWord": "just", "start": 3.76, "end": 4.02, "pageWordId": "p1-6", "matchType": "matched" },
  { "audioWord": "as", "start": 4.02, "end": 4.24, "pageWordId": "p1-7", "matchType": "matched" },
  { "audioWord": "latitude", "start": 4.24, "end": 4.7, "pageWordId": "p1-8", "matchType": "matched" },
  { "audioWord": "has", "start": 4.7, "end": 5.26, "pageWordId": "p1-9", "matchType": "matched" },
  { "audioWord": "the", "start": 5.26, "end": 5.6, "pageWordId": "p1-10", "matchType": "matched" },
  { "audioWord": "equator.", "start": 5.6, "end": 5.92, "pageWordId": "p1-11", "matchType": "matched" },
  { "audioWord": "That", "start": 6.74, "end": 7.02, "pageWordId": "p1-12", "matchType": "matched" },
  { "audioWord": "line", "start": 7.02, "end": 7.34, "pageWordId": "p1-13", "matchType": "matched" },
  { "audioWord": "is", "start": 7.34, "end": 7.82, "pageWordId": "p1-14", "matchType": "matched" },
  { "audioWord": "the", "start": 7.82, "end": 8.14, "pageWordId": "p1-15", "matchType": "matched" },
  { "audioWord": "prime", "start": 8.14, "end": 8.46, "pageWordId": "p1-16", "matchType": "matched" },
  { "audioWord": "meridian.", "start": 8.46, "end": 8.98, "pageWordId": "p1-17", "matchType": "matched" },

  // p2: "In **1884**, nations agreed that the meridian passing through **Greenwich**, in London, would be the international standard — so it is also called the **Greenwich** **Meridian**. It is marked **0°** **longitude**."
  { "audioWord": "In", "start": 9.84, "end": 10.08, "pageWordId": "p2-1", "matchType": "matched" },
  { "audioWord": "1884,", "start": 10.08, "end": 11.04, "pageWordId": "p2-2", "matchType": "matched" },
  { "audioWord": "nations", "start": 11.7, "end": 11.82, "pageWordId": "p2-3", "matchType": "matched" },
  { "audioWord": "agreed", "start": 11.82, "end": 12.32, "pageWordId": "p2-4", "matchType": "matched" },
  { "audioWord": "that", "start": 12.32, "end": 12.6, "pageWordId": "p2-5", "matchType": "matched" },
  { "audioWord": "the", "start": 12.6, "end": 12.8, "pageWordId": "p2-6", "matchType": "matched" },
  { "audioWord": "meridian", "start": 12.8, "end": 13.18, "pageWordId": "p2-7", "matchType": "matched" },
  { "audioWord": "passing", "start": 13.18, "end": 13.6, "pageWordId": "p2-8", "matchType": "matched" },
  { "audioWord": "through", "start": 13.6, "end": 13.96, "pageWordId": "p2-9", "matchType": "matched" },
  { "audioWord": "Greenwich", "start": 13.96, "end": 14.38, "pageWordId": "p2-10", "matchType": "matched" },
  { "audioWord": "in", "start": 14.38, "end": 14.64, "pageWordId": "p2-11", "matchType": "matched" },
  { "audioWord": "London", "start": 14.64, "end": 15.1, "pageWordId": "p2-12", "matchType": "matched" },
  { "audioWord": "would", "start": 15.1, "end": 15.68, "pageWordId": "p2-13", "matchType": "matched" },
  { "audioWord": "be", "start": 15.68, "end": 15.94, "pageWordId": "p2-14", "matchType": "matched" },
  { "audioWord": "the", "start": 15.94, "end": 16.22, "pageWordId": "p2-15", "matchType": "matched" },
  { "audioWord": "international", "start": 16.22, "end": 16.72, "pageWordId": "p2-16", "matchType": "matched" },
  { "audioWord": "standard,", "start": 16.72, "end": 17.2, "pageWordId": "p2-17", "matchType": "matched" },
  { "audioWord": "so", "start": 17.82, "end": 18.0, "pageWordId": "p2-19", "matchType": "matched" },
  { "audioWord": "it", "start": 18.0, "end": 18.14, "pageWordId": "p2-20", "matchType": "matched" },
  { "audioWord": "is", "start": 18.14, "end": 18.36, "pageWordId": "p2-21", "matchType": "matched" },
  { "audioWord": "also", "start": 18.36, "end": 18.64, "pageWordId": "p2-22", "matchType": "matched" },
  { "audioWord": "called", "start": 18.64, "end": 19.08, "pageWordId": "p2-23", "matchType": "matched" },
  { "audioWord": "the", "start": 19.08, "end": 19.4, "pageWordId": "p2-24", "matchType": "matched" },
  { "audioWord": "Greenwich", "start": 19.4, "end": 19.82, "pageWordId": "p2-25", "matchType": "matched" },
  { "audioWord": "meridian.", "start": 19.82, "end": 20.3, "pageWordId": "p2-26", "matchType": "matched" },
  { "audioWord": "It", "start": 20.3, "end": 20.84, "pageWordId": "p2-27", "matchType": "matched" },
  { "audioWord": "is", "start": 20.84, "end": 21.16, "pageWordId": "p2-28", "matchType": "matched" },
  { "audioWord": "marked", "start": 21.16, "end": 21.44, "pageWordId": "p2-29", "matchType": "matched" },
  { "audioWord": "0", "start": 21.44, "end": 21.86, "pageWordId": "p2-30", "matchType": "matched" },
  { "audioWord": "degrees", "start": 21.86, "end": 22.32, "pageWordId": "p2-30", "matchType": "matched" },
  { "audioWord": "longitude.", "start": 22.32, "end": 22.9, "pageWordId": "p2-31", "matchType": "matched" }
];
