export const PAGE58_TRANSCRIPT = [
  // h: "India's Ancient Prime Meridian"
  { "audioWord": "India's", "start": 0.0, "end": 0.6, "pageWordId": "h-1", "matchType": "matched" },
  { "audioWord": "ancient", "start": 0.6, "end": 1.18, "pageWordId": "h-2", "matchType": "matched" },
  { "audioWord": "prime", "start": 1.18, "end": 1.58, "pageWordId": "h-3", "matchType": "matched" },
  { "audioWord": "meridian", "start": 1.58, "end": 2.08, "pageWordId": "h-4", "matchType": "matched" },

  // p1: "Travel back more than **1,500** **years!** Long before Greenwich was chosen as the global standard, ancient Indian astronomers needed a central reference line to map the stars and calculate time."
  { "audioWord": "travel", "start": 2.08, "end": 2.5, "pageWordId": "p1-1", "matchType": "matched" },
  { "audioWord": "back", "start": 2.5, "end": 3.26, "pageWordId": "p1-2", "matchType": "matched" },
  { "audioWord": "more", "start": 3.26, "end": 3.6, "pageWordId": "p1-3", "matchType": "matched" },
  { "audioWord": "than", "start": 3.6, "end": 3.88, "pageWordId": "p1-4", "matchType": "matched" },
  { "audioWord": "1500", "start": 3.88, "end": 4.84, "pageWordId": "p1-5", "matchType": "matched" },
  { "audioWord": "years,", "start": 4.84, "end": 5.68, "pageWordId": "p1-6", "matchType": "matched" },
  { "audioWord": "long", "start": 6.3, "end": 6.52, "pageWordId": "p1-7", "matchType": "matched" },
  { "audioWord": "before", "start": 6.52, "end": 6.82, "pageWordId": "p1-8", "matchType": "matched" },
  { "audioWord": "Greenwich", "start": 6.82, "end": 7.3, "pageWordId": "p1-9", "matchType": "matched" },
  { "audioWord": "was", "start": 7.3, "end": 7.56, "pageWordId": "p1-10", "matchType": "matched" },
  { "audioWord": "chosen", "start": 7.56, "end": 7.98, "pageWordId": "p1-11", "matchType": "matched" },
  { "audioWord": "as", "start": 7.98, "end": 8.36, "pageWordId": "p1-12", "matchType": "matched" },
  { "audioWord": "the", "start": 8.36, "end": 8.62, "pageWordId": "p1-13", "matchType": "matched" },
  { "audioWord": "global", "start": 8.62, "end": 8.94, "pageWordId": "p1-14", "matchType": "matched" },
  { "audioWord": "standard,", "start": 8.94, "end": 9.5, "pageWordId": "p1-15", "matchType": "matched" },
  { "audioWord": "ancient", "start": 10.22, "end": 10.44, "pageWordId": "p1-16", "matchType": "matched" },
  { "audioWord": "Indian", "start": 10.44, "end": 10.82, "pageWordId": "p1-17", "matchType": "matched" },
  { "audioWord": "astronomers", "start": 10.82, "end": 11.52, "pageWordId": "p1-18", "matchType": "matched" },
  { "audioWord": "needed", "start": 11.52, "end": 12.14, "pageWordId": "p1-19", "matchType": "matched" },
  { "audioWord": "a", "start": 12.14, "end": 12.46, "pageWordId": "p1-20", "matchType": "matched" },
  { "audioWord": "central", "start": 12.46, "end": 12.8, "pageWordId": "p1-21", "matchType": "matched" },
  { "audioWord": "reference", "start": 12.8, "end": 13.2, "pageWordId": "p1-22", "matchType": "matched" },
  { "audioWord": "line", "start": 13.2, "end": 13.58, "pageWordId": "p1-23", "matchType": "matched" },
  { "audioWord": "to", "start": 13.58, "end": 14.1, "pageWordId": "p1-24", "matchType": "matched" },
  { "audioWord": "map", "start": 14.1, "end": 14.34, "pageWordId": "p1-25", "matchType": "matched" },
  { "audioWord": "the", "start": 14.34, "end": 14.62, "pageWordId": "p1-26", "matchType": "matched" },
  { "audioWord": "stars", "start": 14.62, "end": 14.94, "pageWordId": "p1-27", "matchType": "matched" },
  { "audioWord": "and", "start": 14.94, "end": 15.36, "pageWordId": "p1-28", "matchType": "matched" },
  { "audioWord": "calculate", "start": 15.36, "end": 15.86, "pageWordId": "p1-29", "matchType": "matched" },
  { "audioWord": "time.", "start": 15.86, "end": 16.26, "pageWordId": "p1-30", "matchType": "matched" },

  // p2: "They established their own Prime Meridian running through the ancient city of **Ujjayini** (modern-day Ujjain). Great scholars like **Aryabhata** and **Varahamihira** used this central meridian for all their brilliant astronomical calculations."
  { "audioWord": "They", "start": 16.9, "end": 17.16, "pageWordId": "p2-1", "matchType": "matched" },
  { "audioWord": "established", "start": 17.16, "end": 17.68, "pageWordId": "p2-2", "matchType": "matched" },
  { "audioWord": "their", "start": 17.68, "end": 18.02, "pageWordId": "p2-3", "matchType": "matched" },
  { "audioWord": "own", "start": 18.02, "end": 18.32, "pageWordId": "p2-4", "matchType": "matched" },
  { "audioWord": "prime", "start": 18.32, "end": 18.6, "pageWordId": "p2-5", "matchType": "matched" },
  { "audioWord": "meridian", "start": 18.6, "end": 19.06, "pageWordId": "p2-6", "matchType": "matched" },
  { "audioWord": "running", "start": 19.06, "end": 19.84, "pageWordId": "p2-7", "matchType": "matched" },
  { "audioWord": "through", "start": 19.84, "end": 20.16, "pageWordId": "p2-8", "matchType": "matched" },
  { "audioWord": "the", "start": 20.16, "end": 20.46, "pageWordId": "p2-9", "matchType": "matched" },
  { "audioWord": "ancient", "start": 20.46, "end": 20.74, "pageWordId": "p2-10", "matchType": "matched" },
  { "audioWord": "city", "start": 20.74, "end": 21.1, "pageWordId": "p2-11", "matchType": "matched" },
  { "audioWord": "of", "start": 21.1, "end": 21.4, "pageWordId": "p2-12", "matchType": "matched" },
  { "audioWord": "Ujjaini,", "start": 21.4, "end": 22.36, "pageWordId": "p2-13", "matchType": "matched" },
  { "audioWord": "modern", "start": 22.62, "end": 22.84, "pageWordId": "p2-14", "matchType": "matched" },
  { "audioWord": "-day", "start": 22.84, "end": 23.08, "pageWordId": "p2-14", "matchType": "matched" },
  { "audioWord": "Ujjain.", "start": 23.08, "end": 23.58, "pageWordId": "p2-15", "matchType": "matched" },
  { "audioWord": "Great", "start": 24.4, "end": 24.9, "pageWordId": "p2-16", "matchType": "matched" },
  { "audioWord": "scholars", "start": 24.9, "end": 25.54, "pageWordId": "p2-17", "matchType": "matched" },
  { "audioWord": "like", "start": 25.54, "end": 26.14, "pageWordId": "p2-18", "matchType": "matched" },
  { "audioWord": "Aryabhata", "start": 26.14, "end": 26.88, "pageWordId": "p2-19", "matchType": "matched" },
  { "audioWord": "and", "start": 26.88, "end": 27.28, "pageWordId": "p2-20", "matchType": "matched" },
  { "audioWord": "Varahamihira", "start": 27.28, "end": 28.38, "pageWordId": "p2-21", "matchType": "matched" },
  { "audioWord": "used", "start": 28.38, "end": 28.96, "pageWordId": "p2-22", "matchType": "matched" },
  { "audioWord": "this", "start": 28.96, "end": 29.42, "pageWordId": "p2-23", "matchType": "matched" },
  { "audioWord": "central", "start": 29.42, "end": 29.82, "pageWordId": "p2-24", "matchType": "matched" },
  { "audioWord": "meridian", "start": 29.82, "end": 30.26, "pageWordId": "p2-25", "matchType": "matched" },
  { "audioWord": "for", "start": 30.26, "end": 30.6, "pageWordId": "p2-26", "matchType": "matched" },
  { "audioWord": "all", "start": 30.6, "end": 30.82, "pageWordId": "p2-27", "matchType": "matched" },
  { "audioWord": "their", "start": 30.82, "end": 31.04, "pageWordId": "p2-28", "matchType": "matched" },
  { "audioWord": "brilliant", "start": 31.04, "end": 31.54, "pageWordId": "p2-29", "matchType": "matched" },
  { "audioWord": "astronomical", "start": 31.54, "end": 32.4, "pageWordId": "p2-30", "matchType": "matched" },
  { "audioWord": "calculations.", "start": 32.4, "end": 33.14, "pageWordId": "p2-31", "matchType": "matched" }
];
